<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


//It's possible to define interface manually. If you would like do it, uncomment following lines:
/*$def = array (
  			 array (
  				 "name"=>"SALESDOCUMENT",
  				 "type"=>"EXPORT",
  				 "optional"=>"0",
  				 "def"=> array (
  					 array ("name"=>"","abap"=>"C","len"=>10,"dec"=>0,"offset"=>0)
  					)
  			),
  			 array (
  				 "name"=>"BEHAVE_WHEN_ERROR",
  				 "type"=>"IMPORT",
  				 "optional"=>"1",
  				 "def"=> array (
  					 array ("name"=>"","abap"=>"C","len"=>1,"dec"=>0,"offset"=>0)
  					)
  			),
  			 array (
  				 "name"=>"BINARY_RELATIONSHIPTYPE",
  				 "type"=>"IMPORT",
  				 "optional"=>"1",
  				 "def"=> array (
  					 array ("name"=>"","abap"=>"C","len"=>4,"dec"=>0,"offset"=>0)
  					)
  			),
  			 array (
  				 "name"=>"CONVERT",
  				 "type"=>"IMPORT",
  				 "optional"=>"1",
  				 "def"=> array (
  					 array ("name"=>"","abap"=>"C","len"=>1,"dec"=>0,"offset"=>0)
  					)
  			),
  			 array (
  				 "name"=>"INT_NUMBER_ASSIGNMENT",
  				 "type"=>"IMPORT",
  				 "optional"=>"1",
  				 "def"=> array (
  					 array ("name"=>"","abap"=>"C","len"=>1,"dec"=>0,"offset"=>0)
  					)
  			),
  			 array (
  				 "name"=>"LOGIC_SWITCH",
  				 "type"=>"IMPORT",
  				 "optional"=>"0",
  				 "def"=> array (
  					 array ("name"=>"PRICING","abap"=>"C","len"=>1,"dec"=>0,"offset"=>0),
  					 array ("name"=>"ATP_WRKMOD","abap"=>"C","len"=>1,"dec"=>0,"offset"=>1),
  					 array ("name"=>"SCHEDULING","abap"=>"C","len"=>1,"dec"=>0,"offset"=>2),
  					 array ("name"=>"NOSTRUCTURE","abap"=>"C","len"=>1,"dec"=>0,"offset"=>3),
  					 array ("name"=>"COND_HANDL","abap"=>"C","len"=>1,"dec"=>0,"offset"=>4)
  					)
  			),
  			 array (
  				 "name"=>"ORDER_HEADER_IN",
  				 "type"=>"IMPORT",
  				 "optional"=>"0",
  				 "def"=> array (
  					 array ("name"=>"REFOBJTYPE","abap"=>"C","len"=>10,"dec"=>0,"offset"=>0),
  					 array ("name"=>"REFOBJKEY","abap"=>"C","len"=>70,"dec"=>0,"offset"=>10),
  					 array ("name"=>"REFDOCTYPE","abap"=>"C","len"=>10,"dec"=>0,"offset"=>80),
  					 array ("name"=>"DOC_TYPE","abap"=>"C","len"=>4,"dec"=>0,"offset"=>90),
  					 array ("name"=>"COLLECT_NO","abap"=>"C","len"=>10,"dec"=>0,"offset"=>94),
  					 array ("name"=>"SALES_ORG","abap"=>"C","len"=>4,"dec"=>0,"offset"=>104),
  					 array ("name"=>"DISTR_CHAN","abap"=>"C","len"=>2,"dec"=>0,"offset"=>108),
  					 array ("name"=>"DIVISION","abap"=>"C","len"=>2,"dec"=>0,"offset"=>110),
  					 array ("name"=>"SALES_GRP","abap"=>"C","len"=>3,"dec"=>0,"offset"=>112),
  					 array ("name"=>"SALES_OFF","abap"=>"C","len"=>4,"dec"=>0,"offset"=>115),
  					 array ("name"=>"REQ_DATE_H","abap"=>"D","len"=>8,"dec"=>0,"offset"=>119),
  					 array ("name"=>"DATE_TYPE","abap"=>"C","len"=>1,"dec"=>0,"offset"=>127),
  					 array ("name"=>"PURCH_DATE","abap"=>"D","len"=>8,"dec"=>0,"offset"=>128),
  					 array ("name"=>"PO_METHOD","abap"=>"C","len"=>4,"dec"=>0,"offset"=>136),
  					 array ("name"=>"PO_SUPPLEM","abap"=>"C","len"=>4,"dec"=>0,"offset"=>140),
  					 array ("name"=>"REF_1","abap"=>"C","len"=>12,"dec"=>0,"offset"=>144),
  					 array ("name"=>"NAME","abap"=>"C","len"=>35,"dec"=>0,"offset"=>156),
  					 array ("name"=>"TELEPHONE","abap"=>"C","len"=>16,"dec"=>0,"offset"=>191),
  					 array ("name"=>"PRICE_GRP","abap"=>"C","len"=>2,"dec"=>0,"offset"=>207),
  					 array ("name"=>"CUST_GROUP","abap"=>"C","len"=>2,"dec"=>0,"offset"=>209),
  					 array ("name"=>"SALES_DIST","abap"=>"C","len"=>6,"dec"=>0,"offset"=>211),
  					 array ("name"=>"PRICE_LIST","abap"=>"C","len"=>2,"dec"=>0,"offset"=>217),
  					 array ("name"=>"INCOTERMS1","abap"=>"C","len"=>3,"dec"=>0,"offset"=>219),
  					 array ("name"=>"INCOTERMS2","abap"=>"C","len"=>28,"dec"=>0,"offset"=>222),
  					 array ("name"=>"PMNTTRMS","abap"=>"C","len"=>4,"dec"=>0,"offset"=>250),
  					 array ("name"=>"DLV_BLOCK","abap"=>"C","len"=>2,"dec"=>0,"offset"=>254),
  					 array ("name"=>"BILL_BLOCK","abap"=>"C","len"=>2,"dec"=>0,"offset"=>256),
  					 array ("name"=>"ORD_REASON","abap"=>"C","len"=>3,"dec"=>0,"offset"=>258),
  					 array ("name"=>"COMPL_DLV","abap"=>"C","len"=>1,"dec"=>0,"offset"=>261),
  					 array ("name"=>"PRICE_DATE","abap"=>"D","len"=>8,"dec"=>0,"offset"=>262),
  					 array ("name"=>"QT_VALID_F","abap"=>"D","len"=>8,"dec"=>0,"offset"=>270),
  					 array ("name"=>"QT_VALID_T","abap"=>"D","len"=>8,"dec"=>0,"offset"=>278),
  					 array ("name"=>"CT_VALID_F","abap"=>"D","len"=>8,"dec"=>0,"offset"=>286),
  					 array ("name"=>"CT_VALID_T","abap"=>"D","len"=>8,"dec"=>0,"offset"=>294),
  					 array ("name"=>"CUST_GRP1","abap"=>"C","len"=>3,"dec"=>0,"offset"=>302),
  					 array ("name"=>"CUST_GRP2","abap"=>"C","len"=>3,"dec"=>0,"offset"=>305),
  					 array ("name"=>"CUST_GRP3","abap"=>"C","len"=>3,"dec"=>0,"offset"=>308),
  					 array ("name"=>"CUST_GRP4","abap"=>"C","len"=>3,"dec"=>0,"offset"=>311),
  					 array ("name"=>"CUST_GRP5","abap"=>"C","len"=>3,"dec"=>0,"offset"=>314),
  					 array ("name"=>"PURCH_NO_C","abap"=>"C","len"=>35,"dec"=>0,"offset"=>317),
  					 array ("name"=>"PURCH_NO_S","abap"=>"C","len"=>35,"dec"=>0,"offset"=>352),
  					 array ("name"=>"PO_DAT_S","abap"=>"D","len"=>8,"dec"=>0,"offset"=>387),
  					 array ("name"=>"PO_METH_S","abap"=>"C","len"=>4,"dec"=>0,"offset"=>395),
  					 array ("name"=>"REF_1_S","abap"=>"C","len"=>12,"dec"=>0,"offset"=>399),
  					 array ("name"=>"SD_DOC_CAT","abap"=>"C","len"=>1,"dec"=>0,"offset"=>411),
  					 array ("name"=>"DOC_DATE","abap"=>"D","len"=>8,"dec"=>0,"offset"=>412),
  					 array ("name"=>"WAR_DATE","abap"=>"D","len"=>8,"dec"=>0,"offset"=>420),
  					 array ("name"=>"SHIP_COND","abap"=>"C","len"=>2,"dec"=>0,"offset"=>428),
  					 array ("name"=>"PP_SEARCH","abap"=>"C","len"=>40,"dec"=>0,"offset"=>430),
  					 array ("name"=>"DUN_COUNT","abap"=>"P","len"=>2,"dec"=>0,"offset"=>470),
  					 array ("name"=>"DUN_DATE","abap"=>"D","len"=>8,"dec"=>0,"offset"=>472),
  					 array ("name"=>"DLVSCHDUSE","abap"=>"C","len"=>3,"dec"=>0,"offset"=>480),
  					 array ("name"=>"PLDLVSTYP","abap"=>"C","len"=>1,"dec"=>0,"offset"=>483),
  					 array ("name"=>"REF_DOC","abap"=>"C","len"=>10,"dec"=>0,"offset"=>484),
  					 array ("name"=>"COMP_CDE_B","abap"=>"C","len"=>4,"dec"=>0,"offset"=>494),
  					 array ("name"=>"ALTTAX_CLS","abap"=>"C","len"=>1,"dec"=>0,"offset"=>498),
  					 array ("name"=>"TAX_CLASS2","abap"=>"C","len"=>1,"dec"=>0,"offset"=>499),
  					 array ("name"=>"TAX_CLASS3","abap"=>"C","len"=>1,"dec"=>0,"offset"=>500),
  					 array ("name"=>"TAX_CLASS4","abap"=>"C","len"=>1,"dec"=>0,"offset"=>501),
  					 array ("name"=>"TAX_CLASS5","abap"=>"C","len"=>1,"dec"=>0,"offset"=>502),
  					 array ("name"=>"TAX_CLASS6","abap"=>"C","len"=>1,"dec"=>0,"offset"=>503),
  					 array ("name"=>"TAX_CLASS7","abap"=>"C","len"=>1,"dec"=>0,"offset"=>504),
  					 array ("name"=>"TAX_CLASS8","abap"=>"C","len"=>1,"dec"=>0,"offset"=>505),
  					 array ("name"=>"TAX_CLASS9","abap"=>"C","len"=>1,"dec"=>0,"offset"=>506),
  					 array ("name"=>"REF_DOC_L","abap"=>"C","len"=>16,"dec"=>0,"offset"=>507),
  					 array ("name"=>"ASS_NUMBER","abap"=>"C","len"=>18,"dec"=>0,"offset"=>523),
  					 array ("name"=>"REFDOC_CAT","abap"=>"C","len"=>1,"dec"=>0,"offset"=>541),
  					 array ("name"=>"ORDCOMB_IN","abap"=>"C","len"=>1,"dec"=>0,"offset"=>542),
  					 array ("name"=>"BILL_SCHED","abap"=>"C","len"=>2,"dec"=>0,"offset"=>543),
  					 array ("name"=>"INVO_SCHED","abap"=>"C","len"=>2,"dec"=>0,"offset"=>545),
  					 array ("name"=>"MN_INVOICE","abap"=>"C","len"=>1,"dec"=>0,"offset"=>547),
  					 array ("name"=>"EXRATE_FI","abap"=>"P","len"=>5,"dec"=>5,"offset"=>548),
  					 array ("name"=>"ADD_VAL_DY","abap"=>"N","len"=>2,"dec"=>0,"offset"=>553),
  					 array ("name"=>"FIX_VAL_DY","abap"=>"D","len"=>8,"dec"=>0,"offset"=>555),
  					 array ("name"=>"PYMT_METH","abap"=>"C","len"=>1,"dec"=>0,"offset"=>563),
  					 array ("name"=>"ACCNT_ASGN","abap"=>"C","len"=>2,"dec"=>0,"offset"=>564),
  					 array ("name"=>"EXCHG_RATE","abap"=>"P","len"=>5,"dec"=>5,"offset"=>566),
  					 array ("name"=>"BILL_DATE","abap"=>"D","len"=>8,"dec"=>0,"offset"=>571),
  					 array ("name"=>"SERV_DATE","abap"=>"D","len"=>8,"dec"=>0,"offset"=>579),
  					 array ("name"=>"DUNN_KEY","abap"=>"C","len"=>1,"dec"=>0,"offset"=>587),
  					 array ("name"=>"DUNN_BLOCK","abap"=>"C","len"=>1,"dec"=>0,"offset"=>588),
  					 array ("name"=>"PMTGAR_PRO","abap"=>"C","len"=>6,"dec"=>0,"offset"=>589),
  					 array ("name"=>"DEPARTM_NO","abap"=>"C","len"=>4,"dec"=>0,"offset"=>595),
  					 array ("name"=>"REC_POINT","abap"=>"C","len"=>25,"dec"=>0,"offset"=>599),
  					 array ("name"=>"DOC_NUM_FI","abap"=>"C","len"=>10,"dec"=>0,"offset"=>624),
  					 array ("name"=>"CSTCNDGRP1","abap"=>"C","len"=>2,"dec"=>0,"offset"=>634),
  					 array ("name"=>"CSTCNDGRP2","abap"=>"C","len"=>2,"dec"=>0,"offset"=>636),
  					 array ("name"=>"CSTCNDGRP3","abap"=>"C","len"=>2,"dec"=>0,"offset"=>638),
  					 array ("name"=>"CSTCNDGRP4","abap"=>"C","len"=>2,"dec"=>0,"offset"=>640),
  					 array ("name"=>"CSTCNDGRP5","abap"=>"C","len"=>2,"dec"=>0,"offset"=>642),
  					 array ("name"=>"DLV_TIME","abap"=>"C","len"=>3,"dec"=>0,"offset"=>644),
  					 array ("name"=>"CURRENCY","abap"=>"C","len"=>5,"dec"=>0,"offset"=>647),
  					 array ("name"=>"CURR_ISO","abap"=>"C","len"=>3,"dec"=>0,"offset"=>652),
  					 array ("name"=>"CREATED_BY","abap"=>"C","len"=>12,"dec"=>0,"offset"=>655),
  					 array ("name"=>"TAXDEP_CTY","abap"=>"C","len"=>3,"dec"=>0,"offset"=>667),
  					 array ("name"=>"TAXDST_CTY","abap"=>"C","len"=>3,"dec"=>0,"offset"=>670),
  					 array ("name"=>"EUTRI_DEAL","abap"=>"C","len"=>1,"dec"=>0,"offset"=>673),
  					 array ("name"=>"MAST_CONTR","abap"=>"C","len"=>10,"dec"=>0,"offset"=>674),
  					 array ("name"=>"REF_PROC","abap"=>"C","len"=>4,"dec"=>0,"offset"=>684),
  					 array ("name"=>"CHKPRTAUTH","abap"=>"C","len"=>1,"dec"=>0,"offset"=>688),
  					 array ("name"=>"CMLQTY_DAT","abap"=>"D","len"=>8,"dec"=>0,"offset"=>689),
  					 array ("name"=>"VERSION","abap"=>"C","len"=>12,"dec"=>0,"offset"=>697),
  					 array ("name"=>"NOTIF_NO","abap"=>"C","len"=>12,"dec"=>0,"offset"=>709),
  					 array ("name"=>"WBS_ELEM","abap"=>"C","len"=>24,"dec"=>0,"offset"=>721),
  					 array ("name"=>"EXCH_RATE_FI_V","abap"=>"P","len"=>5,"dec"=>5,"offset"=>745),
  					 array ("name"=>"EXCHG_RATE_V","abap"=>"P","len"=>5,"dec"=>5,"offset"=>750),
  					 array ("name"=>"FKK_CONACCT","abap"=>"C","len"=>12,"dec"=>0,"offset"=>755),
  					 array ("name"=>"CAMPAIGN","abap"=>"X","len"=>16,"dec"=>0,"offset"=>767),
  					 array ("name"=>"DOC_CLASS","abap"=>"C","len"=>9,"dec"=>0,"offset"=>783),
  					 array ("name"=>"H_CURR","abap"=>"C","len"=>5,"dec"=>0,"offset"=>792),
  					 array ("name"=>"H_CURR_ISO","abap"=>"C","len"=>3,"dec"=>0,"offset"=>797),
  					 array ("name"=>"SHIP_TYPE","abap"=>"C","len"=>2,"dec"=>0,"offset"=>800),
  					 array ("name"=>"S_PROC_IND","abap"=>"C","len"=>4,"dec"=>0,"offset"=>802),
  					 array ("name"=>"REF_DOC_L_LONG","abap"=>"C","len"=>35,"dec"=>0,"offset"=>806),
  					 array ("name"=>"LINE_TIME","abap"=>"T","len"=>6,"dec"=>0,"offset"=>841),
  					 array ("name"=>"CALC_MOTIVE","abap"=>"C","len"=>2,"dec"=>0,"offset"=>847)
  					)
  			),
  			 array (
  				 "name"=>"ORDER_HEADER_INX",
  				 "type"=>"IMPORT",
  				 "optional"=>"0",
  				 "def"=> array (
  					 array ("name"=>"UPDATEFLAG","abap"=>"C","len"=>1,"dec"=>0,"offset"=>0),
  					 array ("name"=>"DOC_TYPE","abap"=>"C","len"=>1,"dec"=>0,"offset"=>1),
  					 array ("name"=>"COLLECT_NO","abap"=>"C","len"=>1,"dec"=>0,"offset"=>2),
  					 array ("name"=>"SALES_ORG","abap"=>"C","len"=>1,"dec"=>0,"offset"=>3),
  					 array ("name"=>"DISTR_CHAN","abap"=>"C","len"=>1,"dec"=>0,"offset"=>4),
  					 array ("name"=>"DIVISION","abap"=>"C","len"=>1,"dec"=>0,"offset"=>5),
  					 array ("name"=>"SALES_GRP","abap"=>"C","len"=>1,"dec"=>0,"offset"=>6),
  					 array ("name"=>"SALES_OFF","abap"=>"C","len"=>1,"dec"=>0,"offset"=>7),
  					 array ("name"=>"REQ_DATE_H","abap"=>"C","len"=>1,"dec"=>0,"offset"=>8),
  					 array ("name"=>"DATE_TYPE","abap"=>"C","len"=>1,"dec"=>0,"offset"=>9),
  					 array ("name"=>"PURCH_DATE","abap"=>"C","len"=>1,"dec"=>0,"offset"=>10),
  					 array ("name"=>"PO_METHOD","abap"=>"C","len"=>1,"dec"=>0,"offset"=>11),
  					 array ("name"=>"PO_SUPPLEM","abap"=>"C","len"=>1,"dec"=>0,"offset"=>12),
  					 array ("name"=>"REF_1","abap"=>"C","len"=>1,"dec"=>0,"offset"=>13),
  					 array ("name"=>"NAME","abap"=>"C","len"=>1,"dec"=>0,"offset"=>14),
  					 array ("name"=>"TELEPHONE","abap"=>"C","len"=>1,"dec"=>0,"offset"=>15),
  					 array ("name"=>"PRICE_GRP","abap"=>"C","len"=>1,"dec"=>0,"offset"=>16),
  					 array ("name"=>"CUST_GROUP","abap"=>"C","len"=>1,"dec"=>0,"offset"=>17),
  					 array ("name"=>"SALES_DIST","abap"=>"C","len"=>1,"dec"=>0,"offset"=>18),
  					 array ("name"=>"PRICE_LIST","abap"=>"C","len"=>1,"dec"=>0,"offset"=>19),
  					 array ("name"=>"INCOTERMS1","abap"=>"C","len"=>1,"dec"=>0,"offset"=>20),
  					 array ("name"=>"INCOTERMS2","abap"=>"C","len"=>1,"dec"=>0,"offset"=>21),
  					 array ("name"=>"PMNTTRMS","abap"=>"C","len"=>1,"dec"=>0,"offset"=>22),
  					 array ("name"=>"DLV_BLOCK","abap"=>"C","len"=>1,"dec"=>0,"offset"=>23),
  					 array ("name"=>"BILL_BLOCK","abap"=>"C","len"=>1,"dec"=>0,"offset"=>24),
  					 array ("name"=>"ORD_REASON","abap"=>"C","len"=>1,"dec"=>0,"offset"=>25),
  					 array ("name"=>"COMPL_DLV","abap"=>"C","len"=>1,"dec"=>0,"offset"=>26),
  					 array ("name"=>"PRICE_DATE","abap"=>"C","len"=>1,"dec"=>0,"offset"=>27),
  					 array ("name"=>"QT_VALID_F","abap"=>"C","len"=>1,"dec"=>0,"offset"=>28),
  					 array ("name"=>"QT_VALID_T","abap"=>"C","len"=>1,"dec"=>0,"offset"=>29),
  					 array ("name"=>"CT_VALID_F","abap"=>"C","len"=>1,"dec"=>0,"offset"=>30),
  					 array ("name"=>"CT_VALID_T","abap"=>"C","len"=>1,"dec"=>0,"offset"=>31),
  					 array ("name"=>"CUST_GRP1","abap"=>"C","len"=>1,"dec"=>0,"offset"=>32),
  					 array ("name"=>"CUST_GRP2","abap"=>"C","len"=>1,"dec"=>0,"offset"=>33),
  					 array ("name"=>"CUST_GRP3","abap"=>"C","len"=>1,"dec"=>0,"offset"=>34),
  					 array ("name"=>"CUST_GRP4","abap"=>"C","len"=>1,"dec"=>0,"offset"=>35),
  					 array ("name"=>"CUST_GRP5","abap"=>"C","len"=>1,"dec"=>0,"offset"=>36),
  					 array ("name"=>"PURCH_NO_C","abap"=>"C","len"=>1,"dec"=>0,"offset"=>37),
  					 array ("name"=>"PURCH_NO_S","abap"=>"C","len"=>1,"dec"=>0,"offset"=>38),
  					 array ("name"=>"PO_DAT_S","abap"=>"C","len"=>1,"dec"=>0,"offset"=>39),
  					 array ("name"=>"PO_METH_S","abap"=>"C","len"=>1,"dec"=>0,"offset"=>40),
  					 array ("name"=>"REF_1_S","abap"=>"C","len"=>1,"dec"=>0,"offset"=>41),
  					 array ("name"=>"SD_DOC_CAT","abap"=>"C","len"=>1,"dec"=>0,"offset"=>42),
  					 array ("name"=>"DOC_DATE","abap"=>"C","len"=>1,"dec"=>0,"offset"=>43),
  					 array ("name"=>"WAR_DATE","abap"=>"C","len"=>1,"dec"=>0,"offset"=>44),
  					 array ("name"=>"SHIP_COND","abap"=>"C","len"=>1,"dec"=>0,"offset"=>45),
  					 array ("name"=>"PP_SEARCH","abap"=>"C","len"=>1,"dec"=>0,"offset"=>46),
  					 array ("name"=>"DUN_COUNT","abap"=>"C","len"=>1,"dec"=>0,"offset"=>47),
  					 array ("name"=>"DUN_DATE","abap"=>"C","len"=>1,"dec"=>0,"offset"=>48),
  					 array ("name"=>"DLVSCHDUSE","abap"=>"C","len"=>1,"dec"=>0,"offset"=>49),
  					 array ("name"=>"PLDLVSTYP","abap"=>"C","len"=>1,"dec"=>0,"offset"=>50),
  					 array ("name"=>"REF_DOC","abap"=>"C","len"=>1,"dec"=>0,"offset"=>51),
  					 array ("name"=>"COMP_CDE_B","abap"=>"C","len"=>1,"dec"=>0,"offset"=>52),
  					 array ("name"=>"ALTTAX_CLS","abap"=>"C","len"=>1,"dec"=>0,"offset"=>53),
  					 array ("name"=>"TAX_CLASS2","abap"=>"C","len"=>1,"dec"=>0,"offset"=>54),
  					 array ("name"=>"TAX_CLASS3","abap"=>"C","len"=>1,"dec"=>0,"offset"=>55),
  					 array ("name"=>"TAX_CLASS4","abap"=>"C","len"=>1,"dec"=>0,"offset"=>56),
  					 array ("name"=>"TAX_CLASS5","abap"=>"C","len"=>1,"dec"=>0,"offset"=>57),
  					 array ("name"=>"TAX_CLASS6","abap"=>"C","len"=>1,"dec"=>0,"offset"=>58),
  					 array ("name"=>"TAX_CLASS7","abap"=>"C","len"=>1,"dec"=>0,"offset"=>59),
  					 array ("name"=>"TAX_CLASS8","abap"=>"C","len"=>1,"dec"=>0,"offset"=>60),
  					 array ("name"=>"TAX_CLASS9","abap"=>"C","len"=>1,"dec"=>0,"offset"=>61),
  					 array ("name"=>"REF_DOC_L","abap"=>"C","len"=>1,"dec"=>0,"offset"=>62),
  					 array ("name"=>"ASS_NUMBER","abap"=>"C","len"=>1,"dec"=>0,"offset"=>63),
  					 array ("name"=>"REFDOC_CAT","abap"=>"C","len"=>1,"dec"=>0,"offset"=>64),
  					 array ("name"=>"ORDCOMB_IN","abap"=>"C","len"=>1,"dec"=>0,"offset"=>65),
  					 array ("name"=>"BILL_SCHED","abap"=>"C","len"=>1,"dec"=>0,"offset"=>66),
  					 array ("name"=>"INVO_SCHED","abap"=>"C","len"=>1,"dec"=>0,"offset"=>67),
  					 array ("name"=>"MN_INVOICE","abap"=>"C","len"=>1,"dec"=>0,"offset"=>68),
  					 array ("name"=>"EXRATE_FI","abap"=>"C","len"=>1,"dec"=>0,"offset"=>69),
  					 array ("name"=>"ADD_VAL_DY","abap"=>"C","len"=>1,"dec"=>0,"offset"=>70),
  					 array ("name"=>"FIX_VAL_DY","abap"=>"C","len"=>1,"dec"=>0,"offset"=>71),
  					 array ("name"=>"PYMT_METH","abap"=>"C","len"=>1,"dec"=>0,"offset"=>72),
  					 array ("name"=>"ACCNT_ASGN","abap"=>"C","len"=>1,"dec"=>0,"offset"=>73),
  					 array ("name"=>"EXCHG_RATE","abap"=>"C","len"=>1,"dec"=>0,"offset"=>74),
  					 array ("name"=>"BILL_DATE","abap"=>"C","len"=>1,"dec"=>0,"offset"=>75),
  					 array ("name"=>"SERV_DATE","abap"=>"C","len"=>1,"dec"=>0,"offset"=>76),
  					 array ("name"=>"DUNN_KEY","abap"=>"C","len"=>1,"dec"=>0,"offset"=>77),
  					 array ("name"=>"DUNN_BLOCK","abap"=>"C","len"=>1,"dec"=>0,"offset"=>78),
  					 array ("name"=>"PROMOTION","abap"=>"C","len"=>1,"dec"=>0,"offset"=>79),
  					 array ("name"=>"PMTGAR_PRO","abap"=>"C","len"=>1,"dec"=>0,"offset"=>80),
  					 array ("name"=>"DEPARTM_NO","abap"=>"C","len"=>1,"dec"=>0,"offset"=>81),
  					 array ("name"=>"REC_POINT","abap"=>"C","len"=>1,"dec"=>0,"offset"=>82),
  					 array ("name"=>"POITM_NO_S","abap"=>"C","len"=>1,"dec"=>0,"offset"=>83),
  					 array ("name"=>"DOC_NUM_FI","abap"=>"C","len"=>1,"dec"=>0,"offset"=>84),
  					 array ("name"=>"CSTCNDGRP1","abap"=>"C","len"=>1,"dec"=>0,"offset"=>85),
  					 array ("name"=>"CSTCNDGRP2","abap"=>"C","len"=>1,"dec"=>0,"offset"=>86),
  					 array ("name"=>"CSTCNDGRP3","abap"=>"C","len"=>1,"dec"=>0,"offset"=>87),
  					 array ("name"=>"CSTCNDGRP4","abap"=>"C","len"=>1,"dec"=>0,"offset"=>88),
  					 array ("name"=>"CSTCNDGRP5","abap"=>"C","len"=>1,"dec"=>0,"offset"=>89),
  					 array ("name"=>"DLV_TIME","abap"=>"C","len"=>1,"dec"=>0,"offset"=>90),
  					 array ("name"=>"CURRENCY","abap"=>"C","len"=>1,"dec"=>0,"offset"=>91),
  					 array ("name"=>"TAXDEP_CTY","abap"=>"C","len"=>1,"dec"=>0,"offset"=>92),
  					 array ("name"=>"TAXDST_CTY","abap"=>"C","len"=>1,"dec"=>0,"offset"=>93),
  					 array ("name"=>"EUTRI_DEAL","abap"=>"C","len"=>1,"dec"=>0,"offset"=>94),
  					 array ("name"=>"MAST_CONTR","abap"=>"C","len"=>1,"dec"=>0,"offset"=>95),
  					 array ("name"=>"REF_PROC","abap"=>"C","len"=>1,"dec"=>0,"offset"=>96),
  					 array ("name"=>"CHKPRTAUTH","abap"=>"C","len"=>1,"dec"=>0,"offset"=>97),
  					 array ("name"=>"CMLQTY_DAT","abap"=>"C","len"=>1,"dec"=>0,"offset"=>98),
  					 array ("name"=>"VERSION","abap"=>"C","len"=>1,"dec"=>0,"offset"=>99),
  					 array ("name"=>"NOTIF_NO","abap"=>"C","len"=>1,"dec"=>0,"offset"=>100),
  					 array ("name"=>"WBS_ELEM","abap"=>"C","len"=>1,"dec"=>0,"offset"=>101),
  					 array ("name"=>"EXCH_RATE_FI_V","abap"=>"C","len"=>1,"dec"=>0,"offset"=>102),
  					 array ("name"=>"EXCHG_RATE_V","abap"=>"C","len"=>1,"dec"=>0,"offset"=>103),
  					 array ("name"=>"FKK_CONACCT","abap"=>"C","len"=>1,"dec"=>0,"offset"=>104),
  					 array ("name"=>"CAMPAIGN","abap"=>"C","len"=>1,"dec"=>0,"offset"=>105),
  					 array ("name"=>"DOC_CLASS","abap"=>"C","len"=>1,"dec"=>0,"offset"=>106),
  					 array ("name"=>"H_CURR","abap"=>"C","len"=>1,"dec"=>0,"offset"=>107),
  					 array ("name"=>"SHIP_TYPE","abap"=>"C","len"=>1,"dec"=>0,"offset"=>108),
  					 array ("name"=>"S_PROC_IND","abap"=>"C","len"=>1,"dec"=>0,"offset"=>109),
  					 array ("name"=>"LINE_TIME","abap"=>"C","len"=>1,"dec"=>0,"offset"=>110),
  					 array ("name"=>"CALC_MOTIVE","abap"=>"C","len"=>1,"dec"=>0,"offset"=>111)
  					)
  			),
  			 array (
  				 "name"=>"SALESDOCUMENTIN",
  				 "type"=>"IMPORT",
  				 "optional"=>"1",
  				 "def"=> array (
  					 array ("name"=>"","abap"=>"C","len"=>10,"dec"=>0,"offset"=>0)
  					)
  			),
  			 array (
  				 "name"=>"SENDER",
  				 "type"=>"IMPORT",
  				 "optional"=>"0",
  				 "def"=> array (
  					 array ("name"=>"LOG_SYSTEM","abap"=>"C","len"=>10,"dec"=>0,"offset"=>0)
  					)
  			),
  			 array (
  				 "name"=>"TESTRUN",
  				 "type"=>"IMPORT",
  				 "optional"=>"1",
  				 "def"=> array (
  					 array ("name"=>"","abap"=>"C","len"=>1,"dec"=>0,"offset"=>0)
  					)
  			),
  			 array (
  				 "name"=>"EXTENSIONIN",
  				 "type"=>"TABLE",
  				 "optional"=>"0",
  				 "def"=> array (
  					 array ("name"=>"STRUCTURE","abap"=>"C","len"=>30,"dec"=>0,"offset"=>0),
  					 array ("name"=>"VALUEPART1","abap"=>"C","len"=>240,"dec"=>0,"offset"=>30),
  					 array ("name"=>"VALUEPART2","abap"=>"C","len"=>240,"dec"=>0,"offset"=>270),
  					 array ("name"=>"VALUEPART3","abap"=>"C","len"=>240,"dec"=>0,"offset"=>510),
  					 array ("name"=>"VALUEPART4","abap"=>"C","len"=>240,"dec"=>0,"offset"=>750)
  					)
  			),
  			 array (
  				 "name"=>"ORDER_CCARD",
  				 "type"=>"TABLE",
  				 "optional"=>"0",
  				 "def"=> array (
  					 array ("name"=>"CC_TYPE","abap"=>"C","len"=>4,"dec"=>0,"offset"=>0),
  					 array ("name"=>"CC_NUMBER","abap"=>"C","len"=>25,"dec"=>0,"offset"=>4),
  					 array ("name"=>"CC_VALID_T","abap"=>"D","len"=>8,"dec"=>0,"offset"=>29),
  					 array ("name"=>"CC_NAME","abap"=>"C","len"=>40,"dec"=>0,"offset"=>37),
  					 array ("name"=>"BILLAMOUNT","abap"=>"P","len"=>12,"dec"=>4,"offset"=>77),
  					 array ("name"=>"AUTH_FLAG","abap"=>"C","len"=>1,"dec"=>0,"offset"=>89),
  					 array ("name"=>"AUTHAMOUNT","abap"=>"P","len"=>12,"dec"=>4,"offset"=>90),
  					 array ("name"=>"CURRENCY","abap"=>"C","len"=>5,"dec"=>0,"offset"=>102),
  					 array ("name"=>"CURR_ISO","abap"=>"C","len"=>3,"dec"=>0,"offset"=>107),
  					 array ("name"=>"AUTH_DATE","abap"=>"D","len"=>8,"dec"=>0,"offset"=>110),
  					 array ("name"=>"AUTH_TIME","abap"=>"T","len"=>6,"dec"=>0,"offset"=>118),
  					 array ("name"=>"AUTH_CC_NO","abap"=>"C","len"=>10,"dec"=>0,"offset"=>124),
  					 array ("name"=>"AUTH_REFNO","abap"=>"C","len"=>15,"dec"=>0,"offset"=>134),
  					 array ("name"=>"CC_REACT","abap"=>"C","len"=>1,"dec"=>0,"offset"=>149),
  					 array ("name"=>"CC_RE_AMOUNT","abap"=>"P","len"=>12,"dec"=>4,"offset"=>150),
  					 array ("name"=>"GL_ACCOUNT","abap"=>"C","len"=>10,"dec"=>0,"offset"=>162),
  					 array ("name"=>"CC_STAT_EX","abap"=>"C","len"=>1,"dec"=>0,"offset"=>172),
  					 array ("name"=>"CC_REACT_T","abap"=>"C","len"=>40,"dec"=>0,"offset"=>173),
  					 array ("name"=>"VIRT_CARD","abap"=>"C","len"=>1,"dec"=>0,"offset"=>213),
  					 array ("name"=>"MERCHIDCL","abap"=>"C","len"=>15,"dec"=>0,"offset"=>214),
  					 array ("name"=>"PRE_AUTH","abap"=>"C","len"=>1,"dec"=>0,"offset"=>229),
  					 array ("name"=>"CC_SEQ_NO","abap"=>"C","len"=>10,"dec"=>0,"offset"=>230),
  					 array ("name"=>"AMOUNTCHAN","abap"=>"C","len"=>1,"dec"=>0,"offset"=>240),
  					 array ("name"=>"AUTHORTYPE","abap"=>"C","len"=>1,"dec"=>0,"offset"=>241),
  					 array ("name"=>"DATAORIGIN","abap"=>"C","len"=>1,"dec"=>0,"offset"=>242),
  					 array ("name"=>"RADRCHECK1","abap"=>"C","len"=>4,"dec"=>0,"offset"=>243),
  					 array ("name"=>"RADRCHECK2","abap"=>"C","len"=>4,"dec"=>0,"offset"=>247),
  					 array ("name"=>"RADRCHECK3","abap"=>"C","len"=>4,"dec"=>0,"offset"=>251),
  					 array ("name"=>"RCARDCHECK","abap"=>"C","len"=>4,"dec"=>0,"offset"=>255),
  					 array ("name"=>"CC_LIMITED","abap"=>"C","len"=>1,"dec"=>0,"offset"=>259),
  					 array ("name"=>"CC_VERIF_VALUE","abap"=>"C","len"=>6,"dec"=>0,"offset"=>260),
  					 array ("name"=>"CC_CTRL_FIELD","abap"=>"C","len"=>1,"dec"=>0,"offset"=>266),
  					 array ("name"=>"CC_IN_USE_ST","abap"=>"C","len"=>1,"dec"=>0,"offset"=>267)
  					)
  			),
  			 array (
  				 "name"=>"ORDER_CFGS_BLOB",
  				 "type"=>"TABLE",
  				 "optional"=>"0",
  				 "def"=> array (
  					 array ("name"=>"CONFIG_ID","abap"=>"C","len"=>6,"dec"=>0,"offset"=>0),
  					 array ("name"=>"CONTEXT","abap"=>"C","len"=>250,"dec"=>0,"offset"=>6)
  					)
  			),
  			 array (
  				 "name"=>"ORDER_CFGS_INST",
  				 "type"=>"TABLE",
  				 "optional"=>"0",
  				 "def"=> array (
  					 array ("name"=>"CONFIG_ID","abap"=>"C","len"=>6,"dec"=>0,"offset"=>0),
  					 array ("name"=>"INST_ID","abap"=>"C","len"=>8,"dec"=>0,"offset"=>6),
  					 array ("name"=>"OBJ_TYPE","abap"=>"C","len"=>10,"dec"=>0,"offset"=>14),
  					 array ("name"=>"CLASS_TYPE","abap"=>"C","len"=>3,"dec"=>0,"offset"=>24),
  					 array ("name"=>"OBJ_KEY","abap"=>"C","len"=>50,"dec"=>0,"offset"=>27),
  					 array ("name"=>"OBJ_TXT","abap"=>"C","len"=>70,"dec"=>0,"offset"=>77),
  					 array ("name"=>"QUANTITY","abap"=>"C","len"=>15,"dec"=>0,"offset"=>147),
  					 array ("name"=>"AUTHOR","abap"=>"C","len"=>1,"dec"=>0,"offset"=>162),
  					 array ("name"=>"QUANTITY_UNIT","abap"=>"C","len"=>3,"dec"=>0,"offset"=>163),
  					 array ("name"=>"COMPLETE","abap"=>"C","len"=>1,"dec"=>0,"offset"=>166),
  					 array ("name"=>"CONSISTENT","abap"=>"C","len"=>1,"dec"=>0,"offset"=>167),
  					 array ("name"=>"OBJECT_GUID","abap"=>"C","len"=>32,"dec"=>0,"offset"=>168),
  					 array ("name"=>"PERSIST_ID","abap"=>"C","len"=>32,"dec"=>0,"offset"=>200),
  					 array ("name"=>"PERSIST_ID_TYPE","abap"=>"C","len"=>1,"dec"=>0,"offset"=>232)
  					)
  			),
  			 array (
  				 "name"=>"ORDER_CFGS_PART_OF",
  				 "type"=>"TABLE",
  				 "optional"=>"0",
  				 "def"=> array (
  					 array ("name"=>"CONFIG_ID","abap"=>"C","len"=>6,"dec"=>0,"offset"=>0),
  					 array ("name"=>"PARENT_ID","abap"=>"C","len"=>8,"dec"=>0,"offset"=>6),
  					 array ("name"=>"INST_ID","abap"=>"C","len"=>8,"dec"=>0,"offset"=>14),
  					 array ("name"=>"PART_OF_NO","abap"=>"C","len"=>4,"dec"=>0,"offset"=>22),
  					 array ("name"=>"OBJ_TYPE","abap"=>"C","len"=>10,"dec"=>0,"offset"=>26),
  					 array ("name"=>"CLASS_TYPE","abap"=>"C","len"=>3,"dec"=>0,"offset"=>36),
  					 array ("name"=>"OBJ_KEY","abap"=>"C","len"=>50,"dec"=>0,"offset"=>39),
  					 array ("name"=>"AUTHOR","abap"=>"C","len"=>1,"dec"=>0,"offset"=>89),
  					 array ("name"=>"SALES_RELEVANT","abap"=>"C","len"=>1,"dec"=>0,"offset"=>90),
  					 array ("name"=>"PART_OF_GUID","abap"=>"C","len"=>32,"dec"=>0,"offset"=>91)
  					)
  			),
  			 array (
  				 "name"=>"ORDER_CFGS_REF",
  				 "type"=>"TABLE",
  				 "optional"=>"0",
  				 "def"=> array (
  					 array ("name"=>"POSEX","abap"=>"C","len"=>6,"dec"=>0,"offset"=>0),
  					 array ("name"=>"CONFIG_ID","abap"=>"C","len"=>6,"dec"=>0,"offset"=>6),
  					 array ("name"=>"ROOT_ID","abap"=>"C","len"=>8,"dec"=>0,"offset"=>12),
  					 array ("name"=>"SCE","abap"=>"C","len"=>1,"dec"=>0,"offset"=>20),
  					 array ("name"=>"KBNAME","abap"=>"C","len"=>30,"dec"=>0,"offset"=>21),
  					 array ("name"=>"KBVERSION","abap"=>"C","len"=>30,"dec"=>0,"offset"=>51),
  					 array ("name"=>"COMPLETE","abap"=>"C","len"=>1,"dec"=>0,"offset"=>81),
  					 array ("name"=>"CONSISTENT","abap"=>"C","len"=>1,"dec"=>0,"offset"=>82),
  					 array ("name"=>"CFGINFO","abap"=>"C","len"=>250,"dec"=>0,"offset"=>83),
  					 array ("name"=>"KBPROFILE","abap"=>"C","len"=>30,"dec"=>0,"offset"=>333),
  					 array ("name"=>"KBLANGUAGE","abap"=>"C","len"=>1,"dec"=>0,"offset"=>363),
  					 array ("name"=>"CBASE_ID","abap"=>"C","len"=>32,"dec"=>0,"offset"=>364),
  					 array ("name"=>"CBASE_ID_TYPE","abap"=>"C","len"=>1,"dec"=>0,"offset"=>396)
  					)
  			),
  			 array (
  				 "name"=>"ORDER_CFGS_REFINST",
  				 "type"=>"TABLE",
  				 "optional"=>"0",
  				 "def"=> array (
  					 array ("name"=>"POSEX","abap"=>"C","len"=>6,"dec"=>0,"offset"=>0),
  					 array ("name"=>"CONFIG_ID","abap"=>"C","len"=>6,"dec"=>0,"offset"=>6),
  					 array ("name"=>"INST_ID","abap"=>"C","len"=>8,"dec"=>0,"offset"=>12)
  					)
  			),
  			 array (
  				 "name"=>"ORDER_CFGS_VALUE",
  				 "type"=>"TABLE",
  				 "optional"=>"0",
  				 "def"=> array (
  					 array ("name"=>"CONFIG_ID","abap"=>"C","len"=>6,"dec"=>0,"offset"=>0),
  					 array ("name"=>"INST_ID","abap"=>"C","len"=>8,"dec"=>0,"offset"=>6),
  					 array ("name"=>"CHARC","abap"=>"C","len"=>40,"dec"=>0,"offset"=>14),
  					 array ("name"=>"CHARC_TXT","abap"=>"C","len"=>70,"dec"=>0,"offset"=>54),
  					 array ("name"=>"VALUE","abap"=>"C","len"=>40,"dec"=>0,"offset"=>124),
  					 array ("name"=>"VALUE_TXT","abap"=>"C","len"=>70,"dec"=>0,"offset"=>164),
  					 array ("name"=>"AUTHOR","abap"=>"C","len"=>1,"dec"=>0,"offset"=>234),
  					 array ("name"=>"VALUE_TO","abap"=>"C","len"=>40,"dec"=>0,"offset"=>235),
  					 array ("name"=>"VALCODE","abap"=>"C","len"=>1,"dec"=>0,"offset"=>275)
  					)
  			),
  			 array (
  				 "name"=>"ORDER_CFGS_VK",
  				 "type"=>"TABLE",
  				 "optional"=>"0",
  				 "def"=> array (
  					 array ("name"=>"CONFIG_ID","abap"=>"C","len"=>6,"dec"=>0,"offset"=>0),
  					 array ("name"=>"INST_ID","abap"=>"C","len"=>8,"dec"=>0,"offset"=>6),
  					 array ("name"=>"VKEY","abap"=>"C","len"=>26,"dec"=>0,"offset"=>14),
  					 array ("name"=>"FACTOR","abap"=>"C","len"=>15,"dec"=>0,"offset"=>40)
  					)
  			),
  			 array (
  				 "name"=>"ORDER_CONDITIONS_IN",
  				 "type"=>"TABLE",
  				 "optional"=>"0",
  				 "def"=> array (
  					 array ("name"=>"ITM_NUMBER","abap"=>"N","len"=>6,"dec"=>0,"offset"=>0),
  					 array ("name"=>"COND_ST_NO","abap"=>"N","len"=>3,"dec"=>0,"offset"=>6),
  					 array ("name"=>"COND_COUNT","abap"=>"N","len"=>2,"dec"=>0,"offset"=>9),
  					 array ("name"=>"COND_TYPE","abap"=>"C","len"=>4,"dec"=>0,"offset"=>11),
  					 array ("name"=>"COND_VALUE","abap"=>"P","len"=>15,"dec"=>9,"offset"=>15),
  					 array ("name"=>"CURRENCY","abap"=>"C","len"=>5,"dec"=>0,"offset"=>30),
  					 array ("name"=>"COND_UNIT","abap"=>"C","len"=>3,"dec"=>0,"offset"=>35),
  					 array ("name"=>"COND_P_UNT","abap"=>"P","len"=>3,"dec"=>0,"offset"=>38),
  					 array ("name"=>"CURR_ISO","abap"=>"C","len"=>3,"dec"=>0,"offset"=>41),
  					 array ("name"=>"CD_UNT_ISO","abap"=>"C","len"=>3,"dec"=>0,"offset"=>44),
  					 array ("name"=>"REFOBJTYPE","abap"=>"C","len"=>10,"dec"=>0,"offset"=>47),
  					 array ("name"=>"REFOBJKEY","abap"=>"C","len"=>70,"dec"=>0,"offset"=>57),
  					 array ("name"=>"REFLOGSYS","abap"=>"C","len"=>10,"dec"=>0,"offset"=>127),
  					 array ("name"=>"APPLICATIO","abap"=>"C","len"=>2,"dec"=>0,"offset"=>137),
  					 array ("name"=>"CONPRICDAT","abap"=>"D","len"=>8,"dec"=>0,"offset"=>139),
  					 array ("name"=>"CALCTYPCON","abap"=>"C","len"=>1,"dec"=>0,"offset"=>147),
  					 array ("name"=>"CONBASEVAL","abap"=>"P","len"=>15,"dec"=>9,"offset"=>148),
  					 array ("name"=>"CONEXCHRAT","abap"=>"P","len"=>5,"dec"=>5,"offset"=>163),
  					 array ("name"=>"NUMCONVERT","abap"=>"P","len"=>3,"dec"=>0,"offset"=>168),
  					 array ("name"=>"DENOMINATO","abap"=>"P","len"=>3,"dec"=>0,"offset"=>171),
  					 array ("name"=>"CONDTYPE","abap"=>"C","len"=>1,"dec"=>0,"offset"=>174),
  					 array ("name"=>"STAT_CON","abap"=>"C","len"=>1,"dec"=>0,"offset"=>175),
  					 array ("name"=>"SCALETYPE","abap"=>"C","len"=>1,"dec"=>0,"offset"=>176),
  					 array ("name"=>"ACCRUALS","abap"=>"C","len"=>1,"dec"=>0,"offset"=>177),
  					 array ("name"=>"CONINVOLST","abap"=>"C","len"=>1,"dec"=>0,"offset"=>178),
  					 array ("name"=>"CONDORIGIN","abap"=>"C","len"=>1,"dec"=>0,"offset"=>179),
  					 array ("name"=>"GROUPCOND","abap"=>"C","len"=>1,"dec"=>0,"offset"=>180),
  					 array ("name"=>"COND_UPDAT","abap"=>"C","len"=>1,"dec"=>0,"offset"=>181),
  					 array ("name"=>"ACCESS_SEQ","abap"=>"N","len"=>2,"dec"=>0,"offset"=>182),
  					 array ("name"=>"CONDCOUNT","abap"=>"N","len"=>2,"dec"=>0,"offset"=>184),
  					 array ("name"=>"ROUNDOFFDI","abap"=>"P","len"=>15,"dec"=>9,"offset"=>186),
  					 array ("name"=>"CONDVALUE","abap"=>"P","len"=>15,"dec"=>9,"offset"=>201),
  					 array ("name"=>"CURRENCY_2","abap"=>"C","len"=>5,"dec"=>0,"offset"=>216),
  					 array ("name"=>"CURR_ISO_2","abap"=>"C","len"=>3,"dec"=>0,"offset"=>221),
  					 array ("name"=>"CONDCNTRL","abap"=>"C","len"=>1,"dec"=>0,"offset"=>224),
  					 array ("name"=>"CONDISACTI","abap"=>"C","len"=>1,"dec"=>0,"offset"=>225),
  					 array ("name"=>"CONDCLASS","abap"=>"C","len"=>1,"dec"=>0,"offset"=>226),
  					 array ("name"=>"FACTBASVAL","abap"=>"F","len"=>8,"dec"=>0,"offset"=>232),
  					 array ("name"=>"SCALEBASIN","abap"=>"C","len"=>1,"dec"=>0,"offset"=>240),
  					 array ("name"=>"SCALBASVAL","abap"=>"P","len"=>15,"dec"=>9,"offset"=>241),
  					 array ("name"=>"UNITMEASUR","abap"=>"C","len"=>3,"dec"=>0,"offset"=>256),
  					 array ("name"=>"ISO_UNIT","abap"=>"C","len"=>3,"dec"=>0,"offset"=>259),
  					 array ("name"=>"CURRENCKEY","abap"=>"C","len"=>5,"dec"=>0,"offset"=>262),
  					 array ("name"=>"CURRENISO","abap"=>"C","len"=>3,"dec"=>0,"offset"=>267),
  					 array ("name"=>"CONDINCOMP","abap"=>"C","len"=>1,"dec"=>0,"offset"=>270),
  					 array ("name"=>"CONDCONFIG","abap"=>"C","len"=>1,"dec"=>0,"offset"=>271),
  					 array ("name"=>"CONDCHAMAN","abap"=>"C","len"=>1,"dec"=>0,"offset"=>272),
  					 array ("name"=>"COND_NO","abap"=>"C","len"=>10,"dec"=>0,"offset"=>273),
  					 array ("name"=>"TAX_CODE","abap"=>"C","len"=>2,"dec"=>0,"offset"=>283),
  					 array ("name"=>"VARCOND","abap"=>"C","len"=>26,"dec"=>0,"offset"=>285),
  					 array ("name"=>"ACCOUNTKEY","abap"=>"C","len"=>3,"dec"=>0,"offset"=>311),
  					 array ("name"=>"ACCOUNT_KE","abap"=>"C","len"=>3,"dec"=>0,"offset"=>314),
  					 array ("name"=>"WT_WITHCD","abap"=>"C","len"=>2,"dec"=>0,"offset"=>317),
  					 array ("name"=>"STRUCTCOND","abap"=>"C","len"=>1,"dec"=>0,"offset"=>319),
  					 array ("name"=>"FACTCONBAS","abap"=>"F","len"=>8,"dec"=>0,"offset"=>320),
  					 array ("name"=>"CONDCOINHD","abap"=>"N","len"=>2,"dec"=>0,"offset"=>328)
  					)
  			),
  			 array (
  				 "name"=>"ORDER_CONDITIONS_INX",
  				 "type"=>"TABLE",
  				 "optional"=>"0",
  				 "def"=> array (
  					 array ("name"=>"ITM_NUMBER","abap"=>"N","len"=>6,"dec"=>0,"offset"=>0),
  					 array ("name"=>"COND_ST_NO","abap"=>"N","len"=>3,"dec"=>0,"offset"=>6),
  					 array ("name"=>"COND_COUNT","abap"=>"N","len"=>2,"dec"=>0,"offset"=>9),
  					 array ("name"=>"COND_TYPE","abap"=>"C","len"=>4,"dec"=>0,"offset"=>11),
  					 array ("name"=>"UPDATEFLAG","abap"=>"C","len"=>1,"dec"=>0,"offset"=>15),
  					 array ("name"=>"COND_VALUE","abap"=>"C","len"=>1,"dec"=>0,"offset"=>16),
  					 array ("name"=>"CURRENCY","abap"=>"C","len"=>1,"dec"=>0,"offset"=>17),
  					 array ("name"=>"COND_UNIT","abap"=>"C","len"=>1,"dec"=>0,"offset"=>18),
  					 array ("name"=>"COND_P_UNT","abap"=>"C","len"=>1,"dec"=>0,"offset"=>19),
  					 array ("name"=>"VARCOND","abap"=>"C","len"=>26,"dec"=>0,"offset"=>20)
  					)
  			),
  			 array (
  				 "name"=>"ORDER_ITEMS_IN",
  				 "type"=>"TABLE",
  				 "optional"=>"0",
  				 "def"=> array (
  					 array ("name"=>"ITM_NUMBER","abap"=>"N","len"=>6,"dec"=>0,"offset"=>0),
  					 array ("name"=>"HG_LV_ITEM","abap"=>"N","len"=>6,"dec"=>0,"offset"=>6),
  					 array ("name"=>"PO_ITM_NO","abap"=>"C","len"=>6,"dec"=>0,"offset"=>12),
  					 array ("name"=>"MATERIAL","abap"=>"C","len"=>18,"dec"=>0,"offset"=>18),
  					 array ("name"=>"ALT_TO_ITM","abap"=>"N","len"=>6,"dec"=>0,"offset"=>36),
  					 array ("name"=>"CUST_MAT22","abap"=>"C","len"=>22,"dec"=>0,"offset"=>42),
  					 array ("name"=>"BATCH","abap"=>"C","len"=>10,"dec"=>0,"offset"=>64),
  					 array ("name"=>"DLV_GROUP","abap"=>"N","len"=>3,"dec"=>0,"offset"=>74),
  					 array ("name"=>"PART_DLV","abap"=>"C","len"=>1,"dec"=>0,"offset"=>77),
  					 array ("name"=>"REASON_REJ","abap"=>"C","len"=>2,"dec"=>0,"offset"=>78),
  					 array ("name"=>"BILL_BLOCK","abap"=>"C","len"=>2,"dec"=>0,"offset"=>80),
  					 array ("name"=>"BILL_DATE","abap"=>"D","len"=>8,"dec"=>0,"offset"=>82),
  					 array ("name"=>"PLANT","abap"=>"C","len"=>4,"dec"=>0,"offset"=>90),
  					 array ("name"=>"STORE_LOC","abap"=>"C","len"=>4,"dec"=>0,"offset"=>94),
  					 array ("name"=>"TARGET_QTY","abap"=>"P","len"=>7,"dec"=>3,"offset"=>98),
  					 array ("name"=>"TARGET_QU","abap"=>"C","len"=>3,"dec"=>0,"offset"=>105),
  					 array ("name"=>"T_UNIT_ISO","abap"=>"C","len"=>3,"dec"=>0,"offset"=>108),
  					 array ("name"=>"ITEM_CATEG","abap"=>"C","len"=>4,"dec"=>0,"offset"=>111),
  					 array ("name"=>"SHORT_TEXT","abap"=>"C","len"=>40,"dec"=>0,"offset"=>115),
  					 array ("name"=>"PRC_GROUP1","abap"=>"C","len"=>3,"dec"=>0,"offset"=>155),
  					 array ("name"=>"PRC_GROUP2","abap"=>"C","len"=>3,"dec"=>0,"offset"=>158),
  					 array ("name"=>"PRC_GROUP3","abap"=>"C","len"=>3,"dec"=>0,"offset"=>161),
  					 array ("name"=>"PRC_GROUP4","abap"=>"C","len"=>3,"dec"=>0,"offset"=>164),
  					 array ("name"=>"PRC_GROUP5","abap"=>"C","len"=>3,"dec"=>0,"offset"=>167),
  					 array ("name"=>"PROD_HIERA","abap"=>"C","len"=>18,"dec"=>0,"offset"=>170),
  					 array ("name"=>"MATL_GROUP","abap"=>"C","len"=>9,"dec"=>0,"offset"=>188),
  					 array ("name"=>"PURCH_NO_C","abap"=>"C","len"=>35,"dec"=>0,"offset"=>197),
  					 array ("name"=>"PURCH_DATE","abap"=>"D","len"=>8,"dec"=>0,"offset"=>232),
  					 array ("name"=>"PO_METHOD","abap"=>"C","len"=>4,"dec"=>0,"offset"=>240),
  					 array ("name"=>"REF_1","abap"=>"C","len"=>12,"dec"=>0,"offset"=>244),
  					 array ("name"=>"PURCH_NO_S","abap"=>"C","len"=>35,"dec"=>0,"offset"=>256),
  					 array ("name"=>"PO_DAT_S","abap"=>"D","len"=>8,"dec"=>0,"offset"=>291),
  					 array ("name"=>"PO_METH_S","abap"=>"C","len"=>4,"dec"=>0,"offset"=>299),
  					 array ("name"=>"REF_1_S","abap"=>"C","len"=>12,"dec"=>0,"offset"=>303),
  					 array ("name"=>"POITM_NO_S","abap"=>"C","len"=>6,"dec"=>0,"offset"=>315),
  					 array ("name"=>"PRICE_GRP","abap"=>"C","len"=>2,"dec"=>0,"offset"=>321),
  					 array ("name"=>"CUST_GROUP","abap"=>"C","len"=>2,"dec"=>0,"offset"=>323),
  					 array ("name"=>"SALES_DIST","abap"=>"C","len"=>6,"dec"=>0,"offset"=>325),
  					 array ("name"=>"PRICE_LIST","abap"=>"C","len"=>2,"dec"=>0,"offset"=>331),
  					 array ("name"=>"INCOTERMS1","abap"=>"C","len"=>3,"dec"=>0,"offset"=>333),
  					 array ("name"=>"INCOTERMS2","abap"=>"C","len"=>28,"dec"=>0,"offset"=>336),
  					 array ("name"=>"ORDCOMP_IN","abap"=>"C","len"=>1,"dec"=>0,"offset"=>364),
  					 array ("name"=>"BILL_SCHED","abap"=>"C","len"=>2,"dec"=>0,"offset"=>365),
  					 array ("name"=>"INVO_SCHED","abap"=>"C","len"=>2,"dec"=>0,"offset"=>367),
  					 array ("name"=>"MN_INVOICE","abap"=>"C","len"=>1,"dec"=>0,"offset"=>369),
  					 array ("name"=>"EX_RATE_FI","abap"=>"P","len"=>5,"dec"=>5,"offset"=>370),
  					 array ("name"=>"ADD_VAL_DY","abap"=>"N","len"=>2,"dec"=>0,"offset"=>375),
  					 array ("name"=>"FIX_VAL_DY","abap"=>"D","len"=>8,"dec"=>0,"offset"=>377),
  					 array ("name"=>"PMNTTRMS","abap"=>"C","len"=>4,"dec"=>0,"offset"=>385),
  					 array ("name"=>"PYMT_METH","abap"=>"C","len"=>1,"dec"=>0,"offset"=>389),
  					 array ("name"=>"ACCNT_ASGN","abap"=>"C","len"=>2,"dec"=>0,"offset"=>390),
  					 array ("name"=>"EXCHG_RATE","abap"=>"P","len"=>5,"dec"=>5,"offset"=>392),
  					 array ("name"=>"PRICE_DATE","abap"=>"D","len"=>8,"dec"=>0,"offset"=>397),
  					 array ("name"=>"SERV_DATE","abap"=>"D","len"=>8,"dec"=>0,"offset"=>405),
  					 array ("name"=>"DUNN_KEY","abap"=>"C","len"=>1,"dec"=>0,"offset"=>413),
  					 array ("name"=>"DUNN_BLOCK","abap"=>"C","len"=>1,"dec"=>0,"offset"=>414),
  					 array ("name"=>"PROMOTION","abap"=>"C","len"=>10,"dec"=>0,"offset"=>415),
  					 array ("name"=>"PMTGAR_PRO","abap"=>"C","len"=>6,"dec"=>0,"offset"=>425),
  					 array ("name"=>"DOC_NUM_FI","abap"=>"C","len"=>10,"dec"=>0,"offset"=>431),
  					 array ("name"=>"DEPARTM_NO","abap"=>"C","len"=>4,"dec"=>0,"offset"=>441),
  					 array ("name"=>"REC_POINT","abap"=>"C","len"=>25,"dec"=>0,"offset"=>445),
  					 array ("name"=>"CSTCNDGRP1","abap"=>"C","len"=>2,"dec"=>0,"offset"=>470),
  					 array ("name"=>"CSTCNDGRP2","abap"=>"C","len"=>2,"dec"=>0,"offset"=>472),
  					 array ("name"=>"CSTCNDGRP3","abap"=>"C","len"=>2,"dec"=>0,"offset"=>474),
  					 array ("name"=>"CSTCNDGRP4","abap"=>"C","len"=>2,"dec"=>0,"offset"=>476),
  					 array ("name"=>"CSTCNDGRP5","abap"=>"C","len"=>2,"dec"=>0,"offset"=>478),
  					 array ("name"=>"DLV_TIME","abap"=>"C","len"=>3,"dec"=>0,"offset"=>480),
  					 array ("name"=>"SALES_UNIT","abap"=>"C","len"=>3,"dec"=>0,"offset"=>483),
  					 array ("name"=>"S_UNIT_ISO","abap"=>"C","len"=>3,"dec"=>0,"offset"=>486),
  					 array ("name"=>"TRG_QTY_NO","abap"=>"P","len"=>3,"dec"=>0,"offset"=>489),
  					 array ("name"=>"TRGQTY_DEN","abap"=>"P","len"=>3,"dec"=>0,"offset"=>492),
  					 array ("name"=>"RNDDLV_QTY","abap"=>"P","len"=>7,"dec"=>3,"offset"=>495),
  					 array ("name"=>"MAXDEVAMNT","abap"=>"P","len"=>7,"dec"=>3,"offset"=>502),
  					 array ("name"=>"MAXDEVPER","abap"=>"P","len"=>2,"dec"=>0,"offset"=>509),
  					 array ("name"=>"MAXDEV_DAY","abap"=>"P","len"=>2,"dec"=>0,"offset"=>511),
  					 array ("name"=>"USAGE_IND","abap"=>"C","len"=>3,"dec"=>0,"offset"=>513),
  					 array ("name"=>"FIXED_QUAN","abap"=>"C","len"=>1,"dec"=>0,"offset"=>516),
  					 array ("name"=>"UNLMT_DLV","abap"=>"C","len"=>1,"dec"=>0,"offset"=>517),
  					 array ("name"=>"OVERDLVTOL","abap"=>"P","len"=>2,"dec"=>1,"offset"=>518),
  					 array ("name"=>"UNDDLV_TOL","abap"=>"P","len"=>2,"dec"=>1,"offset"=>520),
  					 array ("name"=>"DIVISION","abap"=>"C","len"=>2,"dec"=>0,"offset"=>522),
  					 array ("name"=>"SALQTYNUM","abap"=>"P","len"=>3,"dec"=>0,"offset"=>524),
  					 array ("name"=>"SALQTYDEN","abap"=>"P","len"=>3,"dec"=>0,"offset"=>527),
  					 array ("name"=>"GROSS_WGHT","abap"=>"P","len"=>8,"dec"=>3,"offset"=>530),
  					 array ("name"=>"NET_WEIGHT","abap"=>"P","len"=>8,"dec"=>3,"offset"=>538),
  					 array ("name"=>"UNTOF_WGHT","abap"=>"C","len"=>3,"dec"=>0,"offset"=>546),
  					 array ("name"=>"UNOF_WTISO","abap"=>"C","len"=>3,"dec"=>0,"offset"=>549),
  					 array ("name"=>"VOLUME","abap"=>"P","len"=>8,"dec"=>3,"offset"=>552),
  					 array ("name"=>"VOLUNIT","abap"=>"C","len"=>3,"dec"=>0,"offset"=>560),
  					 array ("name"=>"VOLUNITISO","abap"=>"C","len"=>3,"dec"=>0,"offset"=>563),
  					 array ("name"=>"DLV_PRIO","abap"=>"N","len"=>2,"dec"=>0,"offset"=>566),
  					 array ("name"=>"SHIP_POINT","abap"=>"C","len"=>4,"dec"=>0,"offset"=>568),
  					 array ("name"=>"ROUTE","abap"=>"C","len"=>6,"dec"=>0,"offset"=>572),
  					 array ("name"=>"CREATED_BY","abap"=>"C","len"=>12,"dec"=>0,"offset"=>578),
  					 array ("name"=>"TAX_CLASS1","abap"=>"C","len"=>1,"dec"=>0,"offset"=>590),
  					 array ("name"=>"TAX_CLASS2","abap"=>"C","len"=>1,"dec"=>0,"offset"=>591),
  					 array ("name"=>"TAX_CLASS3","abap"=>"C","len"=>1,"dec"=>0,"offset"=>592),
  					 array ("name"=>"TAX_CLASS4","abap"=>"C","len"=>1,"dec"=>0,"offset"=>593),
  					 array ("name"=>"TAX_CLASS5","abap"=>"C","len"=>1,"dec"=>0,"offset"=>594),
  					 array ("name"=>"TAX_CLASS6","abap"=>"C","len"=>1,"dec"=>0,"offset"=>595),
  					 array ("name"=>"TAX_CLASS7","abap"=>"C","len"=>1,"dec"=>0,"offset"=>596),
  					 array ("name"=>"TAX_CLASS8","abap"=>"C","len"=>1,"dec"=>0,"offset"=>597),
  					 array ("name"=>"TAX_CLASS9","abap"=>"C","len"=>1,"dec"=>0,"offset"=>598),
  					 array ("name"=>"MAT_PR_GRP","abap"=>"C","len"=>2,"dec"=>0,"offset"=>599),
  					 array ("name"=>"VAL_TYPE","abap"=>"C","len"=>10,"dec"=>0,"offset"=>601),
  					 array ("name"=>"FIXDAT_QTY","abap"=>"C","len"=>1,"dec"=>0,"offset"=>611),
  					 array ("name"=>"BOMEXPL_NO","abap"=>"C","len"=>8,"dec"=>0,"offset"=>612),
  					 array ("name"=>"RESANALKEY","abap"=>"C","len"=>6,"dec"=>0,"offset"=>620),
  					 array ("name"=>"REQMTS_TYP","abap"=>"C","len"=>4,"dec"=>0,"offset"=>626),
  					 array ("name"=>"NO_GR_POST","abap"=>"C","len"=>1,"dec"=>0,"offset"=>630),
  					 array ("name"=>"BUS_TRANST","abap"=>"C","len"=>2,"dec"=>0,"offset"=>631),
  					 array ("name"=>"OVERHD_KEY","abap"=>"C","len"=>6,"dec"=>0,"offset"=>633),
  					 array ("name"=>"CSTG_SHEET","abap"=>"C","len"=>6,"dec"=>0,"offset"=>639),
  					 array ("name"=>"MATFRGTGRP","abap"=>"C","len"=>8,"dec"=>0,"offset"=>645),
  					 array ("name"=>"PLDLVSHDIN","abap"=>"C","len"=>4,"dec"=>0,"offset"=>653),
  					 array ("name"=>"SEQ_NO","abap"=>"C","len"=>35,"dec"=>0,"offset"=>657),
  					 array ("name"=>"BIL_FORM","abap"=>"C","len"=>2,"dec"=>0,"offset"=>692),
  					 array ("name"=>"DLI_PROFIL","abap"=>"C","len"=>8,"dec"=>0,"offset"=>694),
  					 array ("name"=>"REV_TYPE","abap"=>"C","len"=>1,"dec"=>0,"offset"=>702),
  					 array ("name"=>"BEGDEM_PER","abap"=>"C","len"=>1,"dec"=>0,"offset"=>703),
  					 array ("name"=>"PR_REF_MAT","abap"=>"C","len"=>18,"dec"=>0,"offset"=>704),
  					 array ("name"=>"REFOBJTYPE","abap"=>"C","len"=>10,"dec"=>0,"offset"=>722),
  					 array ("name"=>"REFOBJKEY","abap"=>"C","len"=>70,"dec"=>0,"offset"=>732),
  					 array ("name"=>"REFLOGSYS","abap"=>"C","len"=>10,"dec"=>0,"offset"=>802),
  					 array ("name"=>"ORDER_PROB","abap"=>"N","len"=>3,"dec"=>0,"offset"=>812),
  					 array ("name"=>"MAX_PL_DLV","abap"=>"P","len"=>1,"dec"=>0,"offset"=>815),
  					 array ("name"=>"CFOP_CODE","abap"=>"C","len"=>5,"dec"=>0,"offset"=>816),
  					 array ("name"=>"TAXLAWICMS","abap"=>"C","len"=>3,"dec"=>0,"offset"=>821),
  					 array ("name"=>"TAXLAWIPI","abap"=>"C","len"=>3,"dec"=>0,"offset"=>824),
  					 array ("name"=>"SD_TAXCODE","abap"=>"C","len"=>2,"dec"=>0,"offset"=>827),
  					 array ("name"=>"ASSORT_MOD","abap"=>"C","len"=>18,"dec"=>0,"offset"=>829),
  					 array ("name"=>"COMP_QUANT","abap"=>"P","len"=>7,"dec"=>3,"offset"=>847),
  					 array ("name"=>"TARGET_VAL","abap"=>"P","len"=>15,"dec"=>9,"offset"=>854),
  					 array ("name"=>"CURRENCY","abap"=>"C","len"=>5,"dec"=>0,"offset"=>869),
  					 array ("name"=>"CURR_ISO","abap"=>"C","len"=>3,"dec"=>0,"offset"=>874),
  					 array ("name"=>"PROFIT_CTR","abap"=>"C","len"=>10,"dec"=>0,"offset"=>877),
  					 array ("name"=>"ORDERID","abap"=>"C","len"=>12,"dec"=>0,"offset"=>887),
  					 array ("name"=>"WBS_ELEM","abap"=>"C","len"=>24,"dec"=>0,"offset"=>899),
  					 array ("name"=>"DEPREC_PER","abap"=>"P","len"=>3,"dec"=>2,"offset"=>923),
  					 array ("name"=>"REF_DOC","abap"=>"C","len"=>10,"dec"=>0,"offset"=>926),
  					 array ("name"=>"REF_DOC_IT","abap"=>"N","len"=>6,"dec"=>0,"offset"=>936),
  					 array ("name"=>"REF_DOC_CA","abap"=>"C","len"=>1,"dec"=>0,"offset"=>942),
  					 array ("name"=>"CUST_MAT35","abap"=>"C","len"=>35,"dec"=>0,"offset"=>943),
  					 array ("name"=>"EXCH_RATE_FI_V","abap"=>"P","len"=>5,"dec"=>5,"offset"=>978),
  					 array ("name"=>"EXCHG_RATE_V","abap"=>"P","len"=>5,"dec"=>5,"offset"=>983),
  					 array ("name"=>"ITEMGUID_ATP","abap"=>"C","len"=>22,"dec"=>0,"offset"=>988),
  					 array ("name"=>"VAL_CONTR","abap"=>"C","len"=>10,"dec"=>0,"offset"=>1010),
  					 array ("name"=>"VAL_CON_I","abap"=>"N","len"=>6,"dec"=>0,"offset"=>1020),
  					 array ("name"=>"CONFIG_ID","abap"=>"C","len"=>6,"dec"=>0,"offset"=>1026),
  					 array ("name"=>"INST_ID","abap"=>"C","len"=>8,"dec"=>0,"offset"=>1032),
  					 array ("name"=>"MAT_EXT","abap"=>"C","len"=>40,"dec"=>0,"offset"=>1040),
  					 array ("name"=>"MAT_GUID","abap"=>"C","len"=>32,"dec"=>0,"offset"=>1080),
  					 array ("name"=>"MAT_VERS","abap"=>"C","len"=>10,"dec"=>0,"offset"=>1112),
  					 array ("name"=>"P_MAT_EXT","abap"=>"C","len"=>40,"dec"=>0,"offset"=>1122),
  					 array ("name"=>"P_MAT_GUID","abap"=>"C","len"=>32,"dec"=>0,"offset"=>1162),
  					 array ("name"=>"P_MAT_VERS","abap"=>"C","len"=>10,"dec"=>0,"offset"=>1194),
  					 array ("name"=>"FUNC_AREA","abap"=>"C","len"=>4,"dec"=>0,"offset"=>1204),
  					 array ("name"=>"ALTERN_BOM","abap"=>"C","len"=>2,"dec"=>0,"offset"=>1208),
  					 array ("name"=>"FKK_CONACCT","abap"=>"C","len"=>12,"dec"=>0,"offset"=>1210),
  					 array ("name"=>"EAN_UPC","abap"=>"C","len"=>18,"dec"=>0,"offset"=>1222),
  					 array ("name"=>"PRODCAT","abap"=>"C","len"=>10,"dec"=>0,"offset"=>1240),
  					 array ("name"=>"SHIP_TYPE","abap"=>"C","len"=>2,"dec"=>0,"offset"=>1250),
  					 array ("name"=>"S_PROC_IND","abap"=>"C","len"=>4,"dec"=>0,"offset"=>1252),
  					 array ("name"=>"FUNC_AREA_LONG","abap"=>"C","len"=>16,"dec"=>0,"offset"=>1256),
  					 array ("name"=>"BILL_REL","abap"=>"C","len"=>1,"dec"=>0,"offset"=>1272),
  					 array ("name"=>"VW_UEPOS","abap"=>"C","len"=>1,"dec"=>0,"offset"=>1273),
  					 array ("name"=>"CAMPAIGN","abap"=>"X","len"=>16,"dec"=>0,"offset"=>1274),
  					 array ("name"=>"DLVSCHDUSE","abap"=>"C","len"=>3,"dec"=>0,"offset"=>1290),
  					 array ("name"=>"CFOP_LONG","abap"=>"C","len"=>10,"dec"=>0,"offset"=>1293),
  					 array ("name"=>"SELECTION","abap"=>"C","len"=>32,"dec"=>0,"offset"=>1303),
  					 array ("name"=>"MAT_ENTRD","abap"=>"C","len"=>18,"dec"=>0,"offset"=>1335),
  					 array ("name"=>"LOG_SYSTEM_OWN","abap"=>"C","len"=>10,"dec"=>0,"offset"=>1353),
  					 array ("name"=>"ITM_TYPE_USAGE","abap"=>"C","len"=>4,"dec"=>0,"offset"=>1363),
  					 array ("name"=>"TAXLAWISS","abap"=>"C","len"=>3,"dec"=>0,"offset"=>1367),
  					 array ("name"=>"MAT_ENTRD_EXTERNAL","abap"=>"C","len"=>40,"dec"=>0,"offset"=>1370),
  					 array ("name"=>"MAT_ENTRD_GUID","abap"=>"C","len"=>32,"dec"=>0,"offset"=>1410),
  					 array ("name"=>"MAT_ENTRD_VERSION","abap"=>"C","len"=>10,"dec"=>0,"offset"=>1442),
  					 array ("name"=>"LOC_TAXCAT","abap"=>"C","len"=>2,"dec"=>0,"offset"=>1452),
  					 array ("name"=>"LOC_ZEROVAT","abap"=>"C","len"=>1,"dec"=>0,"offset"=>1454),
  					 array ("name"=>"LOC_ACTCODE","abap"=>"C","len"=>2,"dec"=>0,"offset"=>1455),
  					 array ("name"=>"LOC_DISTTYPE","abap"=>"C","len"=>2,"dec"=>0,"offset"=>1457),
  					 array ("name"=>"LOC_TXRELCLAS","abap"=>"C","len"=>10,"dec"=>0,"offset"=>1459),
  					 array ("name"=>"CALC_MOTIVE","abap"=>"C","len"=>2,"dec"=>0,"offset"=>1469),
  					 array ("name"=>"COMPREAS","abap"=>"C","len"=>4,"dec"=>0,"offset"=>1471),
  					 array ("name"=>"FUND","abap"=>"C","len"=>10,"dec"=>0,"offset"=>1475),
  					 array ("name"=>"FUNDS_CTR","abap"=>"C","len"=>16,"dec"=>0,"offset"=>1485),
  					 array ("name"=>"CMMT_ITEM","abap"=>"C","len"=>24,"dec"=>0,"offset"=>1501),
  					 array ("name"=>"GRANT_NBR","abap"=>"C","len"=>20,"dec"=>0,"offset"=>1525),
  					 array ("name"=>"BUDGET_PERIOD","abap"=>"C","len"=>10,"dec"=>0,"offset"=>1545),
  					 array ("name"=>"TAXLAWCOFINS","abap"=>"C","len"=>3,"dec"=>0,"offset"=>1555),
  					 array ("name"=>"TAXLAWPIS","abap"=>"C","len"=>3,"dec"=>0,"offset"=>1558),
  					 array ("name"=>"TREASURY_ACC_SYMBOL","abap"=>"C","len"=>30,"dec"=>0,"offset"=>1561),
  					 array ("name"=>"BUSINESS_EVENT_TCODE","abap"=>"C","len"=>10,"dec"=>0,"offset"=>1591),
  					 array ("name"=>"MODIFICATION_ALLOWED","abap"=>"C","len"=>1,"dec"=>0,"offset"=>1601),
  					 array ("name"=>"CANCELLATION_ALLOWED","abap"=>"C","len"=>1,"dec"=>0,"offset"=>1602),
  					 array ("name"=>"PAYMENT_METHODS","abap"=>"C","len"=>10,"dec"=>0,"offset"=>1603),
  					 array ("name"=>"BUSINESS_PARTNER_NO","abap"=>"C","len"=>6,"dec"=>0,"offset"=>1613),
  					 array ("name"=>"REPORTING_FREQ","abap"=>"C","len"=>3,"dec"=>0,"offset"=>1619)
  					)
  			),
  			 array (
  				 "name"=>"ORDER_ITEMS_INX",
  				 "type"=>"TABLE",
  				 "optional"=>"0",
  				 "def"=> array (
  					 array ("name"=>"ITM_NUMBER","abap"=>"N","len"=>6,"dec"=>0,"offset"=>0),
  					 array ("name"=>"UPDATEFLAG","abap"=>"C","len"=>1,"dec"=>0,"offset"=>6),
  					 array ("name"=>"HG_LV_ITEM","abap"=>"C","len"=>1,"dec"=>0,"offset"=>7),
  					 array ("name"=>"PO_ITM_NO","abap"=>"C","len"=>1,"dec"=>0,"offset"=>8),
  					 array ("name"=>"MATERIAL","abap"=>"C","len"=>1,"dec"=>0,"offset"=>9),
  					 array ("name"=>"ALT_TO_ITM","abap"=>"C","len"=>1,"dec"=>0,"offset"=>10),
  					 array ("name"=>"CUST_MAT22","abap"=>"C","len"=>1,"dec"=>0,"offset"=>11),
  					 array ("name"=>"BATCH","abap"=>"C","len"=>1,"dec"=>0,"offset"=>12),
  					 array ("name"=>"DLV_GROUP","abap"=>"C","len"=>1,"dec"=>0,"offset"=>13),
  					 array ("name"=>"PART_DLV","abap"=>"C","len"=>1,"dec"=>0,"offset"=>14),
  					 array ("name"=>"REASON_REJ","abap"=>"C","len"=>1,"dec"=>0,"offset"=>15),
  					 array ("name"=>"BILL_BLOCK","abap"=>"C","len"=>1,"dec"=>0,"offset"=>16),
  					 array ("name"=>"BILL_DATE","abap"=>"C","len"=>1,"dec"=>0,"offset"=>17),
  					 array ("name"=>"PLANT","abap"=>"C","len"=>1,"dec"=>0,"offset"=>18),
  					 array ("name"=>"STORE_LOC","abap"=>"C","len"=>1,"dec"=>0,"offset"=>19),
  					 array ("name"=>"TARGET_QTY","abap"=>"C","len"=>1,"dec"=>0,"offset"=>20),
  					 array ("name"=>"TARGET_QU","abap"=>"C","len"=>1,"dec"=>0,"offset"=>21),
  					 array ("name"=>"T_UNIT_ISO","abap"=>"C","len"=>1,"dec"=>0,"offset"=>22),
  					 array ("name"=>"ITEM_CATEG","abap"=>"C","len"=>1,"dec"=>0,"offset"=>23),
  					 array ("name"=>"SHORT_TEXT","abap"=>"C","len"=>1,"dec"=>0,"offset"=>24),
  					 array ("name"=>"PRC_GROUP1","abap"=>"C","len"=>1,"dec"=>0,"offset"=>25),
  					 array ("name"=>"PRC_GROUP2","abap"=>"C","len"=>1,"dec"=>0,"offset"=>26),
  					 array ("name"=>"PRC_GROUP3","abap"=>"C","len"=>1,"dec"=>0,"offset"=>27),
  					 array ("name"=>"PRC_GROUP4","abap"=>"C","len"=>1,"dec"=>0,"offset"=>28),
  					 array ("name"=>"PRC_GROUP5","abap"=>"C","len"=>1,"dec"=>0,"offset"=>29),
  					 array ("name"=>"PROD_HIERA","abap"=>"C","len"=>1,"dec"=>0,"offset"=>30),
  					 array ("name"=>"MATL_GROUP","abap"=>"C","len"=>1,"dec"=>0,"offset"=>31),
  					 array ("name"=>"PURCH_NO_C","abap"=>"C","len"=>1,"dec"=>0,"offset"=>32),
  					 array ("name"=>"PURCH_DATE","abap"=>"C","len"=>1,"dec"=>0,"offset"=>33),
  					 array ("name"=>"PO_METHOD","abap"=>"C","len"=>1,"dec"=>0,"offset"=>34),
  					 array ("name"=>"REF_1","abap"=>"C","len"=>1,"dec"=>0,"offset"=>35),
  					 array ("name"=>"PURCH_NO_S","abap"=>"C","len"=>1,"dec"=>0,"offset"=>36),
  					 array ("name"=>"PO_DAT_S","abap"=>"C","len"=>1,"dec"=>0,"offset"=>37),
  					 array ("name"=>"PO_METH_S","abap"=>"C","len"=>1,"dec"=>0,"offset"=>38),
  					 array ("name"=>"REF_1_S","abap"=>"C","len"=>1,"dec"=>0,"offset"=>39),
  					 array ("name"=>"POITM_NO_S","abap"=>"C","len"=>1,"dec"=>0,"offset"=>40),
  					 array ("name"=>"PRICE_GRP","abap"=>"C","len"=>1,"dec"=>0,"offset"=>41),
  					 array ("name"=>"CUST_GROUP","abap"=>"C","len"=>1,"dec"=>0,"offset"=>42),
  					 array ("name"=>"SALES_DIST","abap"=>"C","len"=>1,"dec"=>0,"offset"=>43),
  					 array ("name"=>"PRICE_LIST","abap"=>"C","len"=>1,"dec"=>0,"offset"=>44),
  					 array ("name"=>"INCOTERMS1","abap"=>"C","len"=>1,"dec"=>0,"offset"=>45),
  					 array ("name"=>"INCOTERMS2","abap"=>"C","len"=>1,"dec"=>0,"offset"=>46),
  					 array ("name"=>"ORDCOMP_IN","abap"=>"C","len"=>1,"dec"=>0,"offset"=>47),
  					 array ("name"=>"BILL_SCHED","abap"=>"C","len"=>1,"dec"=>0,"offset"=>48),
  					 array ("name"=>"INVO_SCHED","abap"=>"C","len"=>1,"dec"=>0,"offset"=>49),
  					 array ("name"=>"MN_INVOICE","abap"=>"C","len"=>1,"dec"=>0,"offset"=>50),
  					 array ("name"=>"EX_RATE_FI","abap"=>"C","len"=>1,"dec"=>0,"offset"=>51),
  					 array ("name"=>"ADD_VAL_DY","abap"=>"C","len"=>1,"dec"=>0,"offset"=>52),
  					 array ("name"=>"FIX_VAL_DY","abap"=>"C","len"=>1,"dec"=>0,"offset"=>53),
  					 array ("name"=>"PMNTTRMS","abap"=>"C","len"=>1,"dec"=>0,"offset"=>54),
  					 array ("name"=>"PYMT_METH","abap"=>"C","len"=>1,"dec"=>0,"offset"=>55),
  					 array ("name"=>"ACCNT_ASGN","abap"=>"C","len"=>1,"dec"=>0,"offset"=>56),
  					 array ("name"=>"EXCHG_RATE","abap"=>"C","len"=>1,"dec"=>0,"offset"=>57),
  					 array ("name"=>"PRICE_DATE","abap"=>"C","len"=>1,"dec"=>0,"offset"=>58),
  					 array ("name"=>"SERV_DATE","abap"=>"C","len"=>1,"dec"=>0,"offset"=>59),
  					 array ("name"=>"DUNN_KEY","abap"=>"C","len"=>1,"dec"=>0,"offset"=>60),
  					 array ("name"=>"DUNN_BLOCK","abap"=>"C","len"=>1,"dec"=>0,"offset"=>61),
  					 array ("name"=>"PROMOTION","abap"=>"C","len"=>1,"dec"=>0,"offset"=>62),
  					 array ("name"=>"PMTGAR_PRO","abap"=>"C","len"=>1,"dec"=>0,"offset"=>63),
  					 array ("name"=>"DOC_NUM_FI","abap"=>"C","len"=>1,"dec"=>0,"offset"=>64),
  					 array ("name"=>"DEPARTM_NO","abap"=>"C","len"=>1,"dec"=>0,"offset"=>65),
  					 array ("name"=>"REC_POINT","abap"=>"C","len"=>1,"dec"=>0,"offset"=>66),
  					 array ("name"=>"CSTCNDGRP1","abap"=>"C","len"=>1,"dec"=>0,"offset"=>67),
  					 array ("name"=>"CSTCNDGRP2","abap"=>"C","len"=>1,"dec"=>0,"offset"=>68),
  					 array ("name"=>"CSTCNDGRP3","abap"=>"C","len"=>1,"dec"=>0,"offset"=>69),
  					 array ("name"=>"CSTCNDGRP4","abap"=>"C","len"=>1,"dec"=>0,"offset"=>70),
  					 array ("name"=>"CSTCNDGRP5","abap"=>"C","len"=>1,"dec"=>0,"offset"=>71),
  					 array ("name"=>"DLV_TIME","abap"=>"C","len"=>1,"dec"=>0,"offset"=>72),
  					 array ("name"=>"SALES_UNIT","abap"=>"C","len"=>1,"dec"=>0,"offset"=>73),
  					 array ("name"=>"TRG_QTY_NO","abap"=>"C","len"=>1,"dec"=>0,"offset"=>74),
  					 array ("name"=>"TRGQTY_DEN","abap"=>"C","len"=>1,"dec"=>0,"offset"=>75),
  					 array ("name"=>"RNDDLV_QTY","abap"=>"C","len"=>1,"dec"=>0,"offset"=>76),
  					 array ("name"=>"MAXDEVAMNT","abap"=>"C","len"=>1,"dec"=>0,"offset"=>77),
  					 array ("name"=>"MAXDEVPER","abap"=>"C","len"=>1,"dec"=>0,"offset"=>78),
  					 array ("name"=>"MAXDEV_DAY","abap"=>"C","len"=>1,"dec"=>0,"offset"=>79),
  					 array ("name"=>"USAGE_IND","abap"=>"C","len"=>1,"dec"=>0,"offset"=>80),
  					 array ("name"=>"FIXED_QUAN","abap"=>"C","len"=>1,"dec"=>0,"offset"=>81),
  					 array ("name"=>"UNLMT_DLV","abap"=>"C","len"=>1,"dec"=>0,"offset"=>82),
  					 array ("name"=>"OVERDLVTOL","abap"=>"C","len"=>1,"dec"=>0,"offset"=>83),
  					 array ("name"=>"UNDDLV_TOL","abap"=>"C","len"=>1,"dec"=>0,"offset"=>84),
  					 array ("name"=>"DIVISION","abap"=>"C","len"=>1,"dec"=>0,"offset"=>85),
  					 array ("name"=>"SALQTYNUM","abap"=>"C","len"=>1,"dec"=>0,"offset"=>86),
  					 array ("name"=>"SALQTYDEN","abap"=>"C","len"=>1,"dec"=>0,"offset"=>87),
  					 array ("name"=>"GROSS_WGHT","abap"=>"C","len"=>1,"dec"=>0,"offset"=>88),
  					 array ("name"=>"NET_WEIGHT","abap"=>"C","len"=>1,"dec"=>0,"offset"=>89),
  					 array ("name"=>"UNTOF_WGHT","abap"=>"C","len"=>1,"dec"=>0,"offset"=>90),
  					 array ("name"=>"VOLUME","abap"=>"C","len"=>1,"dec"=>0,"offset"=>91),
  					 array ("name"=>"VOLUNIT","abap"=>"C","len"=>1,"dec"=>0,"offset"=>92),
  					 array ("name"=>"DLV_PRIO","abap"=>"C","len"=>1,"dec"=>0,"offset"=>93),
  					 array ("name"=>"SHIP_POINT","abap"=>"C","len"=>1,"dec"=>0,"offset"=>94),
  					 array ("name"=>"ROUTE","abap"=>"C","len"=>1,"dec"=>0,"offset"=>95),
  					 array ("name"=>"TAX_CLASS1","abap"=>"C","len"=>1,"dec"=>0,"offset"=>96),
  					 array ("name"=>"TAX_CLASS2","abap"=>"C","len"=>1,"dec"=>0,"offset"=>97),
  					 array ("name"=>"TAX_CLASS3","abap"=>"C","len"=>1,"dec"=>0,"offset"=>98),
  					 array ("name"=>"TAX_CLASS4","abap"=>"C","len"=>1,"dec"=>0,"offset"=>99),
  					 array ("name"=>"TAX_CLASS5","abap"=>"C","len"=>1,"dec"=>0,"offset"=>100),
  					 array ("name"=>"TAX_CLASS6","abap"=>"C","len"=>1,"dec"=>0,"offset"=>101),
  					 array ("name"=>"TAX_CLASS7","abap"=>"C","len"=>1,"dec"=>0,"offset"=>102),
  					 array ("name"=>"TAX_CLASS8","abap"=>"C","len"=>1,"dec"=>0,"offset"=>103),
  					 array ("name"=>"TAX_CLASS9","abap"=>"C","len"=>1,"dec"=>0,"offset"=>104),
  					 array ("name"=>"MAT_PR_GRP","abap"=>"C","len"=>1,"dec"=>0,"offset"=>105),
  					 array ("name"=>"VAL_TYPE","abap"=>"C","len"=>1,"dec"=>0,"offset"=>106),
  					 array ("name"=>"FIXDAT_QTY","abap"=>"C","len"=>1,"dec"=>0,"offset"=>107),
  					 array ("name"=>"BOMEXPL_NO","abap"=>"C","len"=>1,"dec"=>0,"offset"=>108),
  					 array ("name"=>"RESANALKEY","abap"=>"C","len"=>1,"dec"=>0,"offset"=>109),
  					 array ("name"=>"REQMTS_TYP","abap"=>"C","len"=>1,"dec"=>0,"offset"=>110),
  					 array ("name"=>"NO_GR_POST","abap"=>"C","len"=>1,"dec"=>0,"offset"=>111),
  					 array ("name"=>"BUS_TRANST","abap"=>"C","len"=>1,"dec"=>0,"offset"=>112),
  					 array ("name"=>"OVERHD_KEY","abap"=>"C","len"=>1,"dec"=>0,"offset"=>113),
  					 array ("name"=>"CSTG_SHEET","abap"=>"C","len"=>1,"dec"=>0,"offset"=>114),
  					 array ("name"=>"MATFRGTGRP","abap"=>"C","len"=>1,"dec"=>0,"offset"=>115),
  					 array ("name"=>"PLDLVSHDIN","abap"=>"C","len"=>1,"dec"=>0,"offset"=>116),
  					 array ("name"=>"SEQ_NO","abap"=>"C","len"=>1,"dec"=>0,"offset"=>117),
  					 array ("name"=>"BIL_FORM","abap"=>"C","len"=>1,"dec"=>0,"offset"=>118),
  					 array ("name"=>"DLI_PROFIL","abap"=>"C","len"=>1,"dec"=>0,"offset"=>119),
  					 array ("name"=>"REV_TYPE","abap"=>"C","len"=>1,"dec"=>0,"offset"=>120),
  					 array ("name"=>"BEGDEM_PER","abap"=>"C","len"=>1,"dec"=>0,"offset"=>121),
  					 array ("name"=>"PR_REF_MAT","abap"=>"C","len"=>1,"dec"=>0,"offset"=>122),
  					 array ("name"=>"REFOBJTYPE","abap"=>"C","len"=>1,"dec"=>0,"offset"=>123),
  					 array ("name"=>"REFOBJKEY","abap"=>"C","len"=>1,"dec"=>0,"offset"=>124),
  					 array ("name"=>"REFLOGSYS","abap"=>"C","len"=>1,"dec"=>0,"offset"=>125),
  					 array ("name"=>"ORDER_PROB","abap"=>"C","len"=>1,"dec"=>0,"offset"=>126),
  					 array ("name"=>"MAX_PL_DLV","abap"=>"C","len"=>1,"dec"=>0,"offset"=>127),
  					 array ("name"=>"CFOP_CODE","abap"=>"C","len"=>1,"dec"=>0,"offset"=>128),
  					 array ("name"=>"TAXLAWICMS","abap"=>"C","len"=>1,"dec"=>0,"offset"=>129),
  					 array ("name"=>"TAXLAWIPI","abap"=>"C","len"=>1,"dec"=>0,"offset"=>130),
  					 array ("name"=>"SD_TAXCODE","abap"=>"C","len"=>1,"dec"=>0,"offset"=>131),
  					 array ("name"=>"ASSORT_MOD","abap"=>"C","len"=>1,"dec"=>0,"offset"=>132),
  					 array ("name"=>"COMP_QUANT","abap"=>"C","len"=>1,"dec"=>0,"offset"=>133),
  					 array ("name"=>"TARGET_VAL","abap"=>"C","len"=>1,"dec"=>0,"offset"=>134),
  					 array ("name"=>"PROFIT_CTR","abap"=>"C","len"=>1,"dec"=>0,"offset"=>135),
  					 array ("name"=>"ORDERID","abap"=>"C","len"=>1,"dec"=>0,"offset"=>136),
  					 array ("name"=>"WBS_ELEM","abap"=>"C","len"=>1,"dec"=>0,"offset"=>137),
  					 array ("name"=>"DEPREC_PER","abap"=>"C","len"=>1,"dec"=>0,"offset"=>138),
  					 array ("name"=>"REF_DOC","abap"=>"C","len"=>1,"dec"=>0,"offset"=>139),
  					 array ("name"=>"REF_DOC_IT","abap"=>"C","len"=>1,"dec"=>0,"offset"=>140),
  					 array ("name"=>"REF_DOC_CA","abap"=>"C","len"=>1,"dec"=>0,"offset"=>141),
  					 array ("name"=>"CUST_MAT35","abap"=>"C","len"=>1,"dec"=>0,"offset"=>142),
  					 array ("name"=>"EXCH_RATE_FI_V","abap"=>"C","len"=>1,"dec"=>0,"offset"=>143),
  					 array ("name"=>"EXCHG_RATE_V","abap"=>"C","len"=>1,"dec"=>0,"offset"=>144),
  					 array ("name"=>"ITEMGUID_ATP","abap"=>"C","len"=>1,"dec"=>0,"offset"=>145),
  					 array ("name"=>"VAL_CONTR","abap"=>"C","len"=>1,"dec"=>0,"offset"=>146),
  					 array ("name"=>"VAL_CON_I","abap"=>"C","len"=>1,"dec"=>0,"offset"=>147),
  					 array ("name"=>"CONFIG_ID","abap"=>"C","len"=>1,"dec"=>0,"offset"=>148),
  					 array ("name"=>"INST_ID","abap"=>"C","len"=>1,"dec"=>0,"offset"=>149),
  					 array ("name"=>"MAT_EXT","abap"=>"C","len"=>1,"dec"=>0,"offset"=>150),
  					 array ("name"=>"MAT_GUID","abap"=>"C","len"=>1,"dec"=>0,"offset"=>151),
  					 array ("name"=>"MAT_VERS","abap"=>"C","len"=>1,"dec"=>0,"offset"=>152),
  					 array ("name"=>"P_MAT_EXT","abap"=>"C","len"=>1,"dec"=>0,"offset"=>153),
  					 array ("name"=>"P_MAT_GUID","abap"=>"C","len"=>1,"dec"=>0,"offset"=>154),
  					 array ("name"=>"P_MAT_VERS","abap"=>"C","len"=>1,"dec"=>0,"offset"=>155),
  					 array ("name"=>"FUNC_AREA","abap"=>"C","len"=>1,"dec"=>0,"offset"=>156),
  					 array ("name"=>"ALTERN_BOM","abap"=>"C","len"=>1,"dec"=>0,"offset"=>157),
  					 array ("name"=>"FKK_CONACCT","abap"=>"C","len"=>1,"dec"=>0,"offset"=>158),
  					 array ("name"=>"EAN_UPC","abap"=>"C","len"=>1,"dec"=>0,"offset"=>159),
  					 array ("name"=>"PRODCAT","abap"=>"C","len"=>1,"dec"=>0,"offset"=>160),
  					 array ("name"=>"SHIP_TYPE","abap"=>"C","len"=>1,"dec"=>0,"offset"=>161),
  					 array ("name"=>"S_PROC_IND","abap"=>"C","len"=>1,"dec"=>0,"offset"=>162),
  					 array ("name"=>"BILL_REL","abap"=>"C","len"=>1,"dec"=>0,"offset"=>163),
  					 array ("name"=>"VW_UEPOS","abap"=>"C","len"=>1,"dec"=>0,"offset"=>164),
  					 array ("name"=>"CAMPAIGN","abap"=>"C","len"=>1,"dec"=>0,"offset"=>165),
  					 array ("name"=>"DLVSCHDUSE","abap"=>"C","len"=>1,"dec"=>0,"offset"=>166),
  					 array ("name"=>"SELECTION","abap"=>"C","len"=>1,"dec"=>0,"offset"=>167),
  					 array ("name"=>"MAT_ENTRD","abap"=>"C","len"=>1,"dec"=>0,"offset"=>168),
  					 array ("name"=>"LOG_SYSTEM_OWN","abap"=>"C","len"=>1,"dec"=>0,"offset"=>169),
  					 array ("name"=>"ITM_TYPE_USAGE","abap"=>"C","len"=>1,"dec"=>0,"offset"=>170),
  					 array ("name"=>"MAT_ENTRD_EXTERNAL","abap"=>"C","len"=>1,"dec"=>0,"offset"=>171),
  					 array ("name"=>"MAT_ENTRD_GUID","abap"=>"C","len"=>1,"dec"=>0,"offset"=>172),
  					 array ("name"=>"MAT_ENTRD_VERSION","abap"=>"C","len"=>1,"dec"=>0,"offset"=>173),
  					 array ("name"=>"LOC_TAXCAT","abap"=>"C","len"=>1,"dec"=>0,"offset"=>174),
  					 array ("name"=>"LOC_ZEROVAT","abap"=>"C","len"=>1,"dec"=>0,"offset"=>175),
  					 array ("name"=>"LOC_ACTCODE","abap"=>"C","len"=>1,"dec"=>0,"offset"=>176),
  					 array ("name"=>"LOC_DISTTYPE","abap"=>"C","len"=>1,"dec"=>0,"offset"=>177),
  					 array ("name"=>"LOC_TXRELCLAS","abap"=>"C","len"=>1,"dec"=>0,"offset"=>178),
  					 array ("name"=>"CALC_MOTIVE","abap"=>"C","len"=>1,"dec"=>0,"offset"=>179),
  					 array ("name"=>"FUND","abap"=>"C","len"=>1,"dec"=>0,"offset"=>180),
  					 array ("name"=>"FUNDS_CTR","abap"=>"C","len"=>1,"dec"=>0,"offset"=>181),
  					 array ("name"=>"CMMT_ITEM","abap"=>"C","len"=>1,"dec"=>0,"offset"=>182),
  					 array ("name"=>"GRANT_NBR","abap"=>"C","len"=>1,"dec"=>0,"offset"=>183),
  					 array ("name"=>"BUDGET_PERIOD","abap"=>"C","len"=>1,"dec"=>0,"offset"=>184),
  					 array ("name"=>"TAXLAWISS","abap"=>"C","len"=>1,"dec"=>0,"offset"=>185),
  					 array ("name"=>"TAXLAWCOFINS","abap"=>"C","len"=>1,"dec"=>0,"offset"=>186),
  					 array ("name"=>"TAXLAWPIS","abap"=>"C","len"=>1,"dec"=>0,"offset"=>187),
  					 array ("name"=>"TREASURY_ACC_SYMBOL","abap"=>"C","len"=>1,"dec"=>0,"offset"=>188),
  					 array ("name"=>"BUSINESS_EVENT_TCODE","abap"=>"C","len"=>1,"dec"=>0,"offset"=>189),
  					 array ("name"=>"MODIFICATION_ALLOWED","abap"=>"C","len"=>1,"dec"=>0,"offset"=>190),
  					 array ("name"=>"CANCELLATION_ALLOWED","abap"=>"C","len"=>1,"dec"=>0,"offset"=>191),
  					 array ("name"=>"PAYMENT_METHODS","abap"=>"C","len"=>1,"dec"=>0,"offset"=>192),
  					 array ("name"=>"BUSINESS_PARTNER_NO","abap"=>"C","len"=>1,"dec"=>0,"offset"=>193),
  					 array ("name"=>"REPORTING_FREQ","abap"=>"C","len"=>1,"dec"=>0,"offset"=>194),
  					 array ("name"=>"CFOP_LONG","abap"=>"C","len"=>1,"dec"=>0,"offset"=>195)
  					)
  			),
  			 array (
  				 "name"=>"ORDER_KEYS",
  				 "type"=>"TABLE",
  				 "optional"=>"0",
  				 "def"=> array (
  					 array ("name"=>"REFOBJTYP","abap"=>"C","len"=>10,"dec"=>0,"offset"=>0),
  					 array ("name"=>"REFOBJECT","abap"=>"C","len"=>32,"dec"=>0,"offset"=>10),
  					 array ("name"=>"REFOBJKEY","abap"=>"C","len"=>70,"dec"=>0,"offset"=>42),
  					 array ("name"=>"REFLOGSYS","abap"=>"C","len"=>10,"dec"=>0,"offset"=>112),
  					 array ("name"=>"DOC_NUMBER","abap"=>"C","len"=>10,"dec"=>0,"offset"=>122),
  					 array ("name"=>"ITM_NUMBER","abap"=>"N","len"=>6,"dec"=>0,"offset"=>132),
  					 array ("name"=>"SCHED_LIN","abap"=>"N","len"=>4,"dec"=>0,"offset"=>138),
  					 array ("name"=>"COND_NO","abap"=>"C","len"=>10,"dec"=>0,"offset"=>142),
  					 array ("name"=>"CONDITEMNO","abap"=>"N","len"=>6,"dec"=>0,"offset"=>152),
  					 array ("name"=>"COND_ST_NO","abap"=>"N","len"=>3,"dec"=>0,"offset"=>158),
  					 array ("name"=>"COND_COUNT","abap"=>"N","len"=>2,"dec"=>0,"offset"=>161),
  					 array ("name"=>"COND_TYPE","abap"=>"C","len"=>4,"dec"=>0,"offset"=>163),
  					 array ("name"=>"STATUS","abap"=>"C","len"=>1,"dec"=>0,"offset"=>167),
  					 array ("name"=>"TINDEX","abap"=>"N","len"=>6,"dec"=>0,"offset"=>168),
  					 array ("name"=>"ADDRESS","abap"=>"C","len"=>10,"dec"=>0,"offset"=>174),
  					 array ("name"=>"ABRLI","abap"=>"N","len"=>4,"dec"=>0,"offset"=>184),
  					 array ("name"=>"ABART","abap"=>"C","len"=>1,"dec"=>0,"offset"=>188)
  					)
  			),
  			 array (
  				 "name"=>"ORDER_PARTNERS",
  				 "type"=>"TABLE",
  				 "optional"=>"0",
  				 "def"=> array (
  					 array ("name"=>"PARTN_ROLE","abap"=>"C","len"=>2,"dec"=>0,"offset"=>0),
  					 array ("name"=>"PARTN_NUMB","abap"=>"C","len"=>10,"dec"=>0,"offset"=>2),
  					 array ("name"=>"ITM_NUMBER","abap"=>"N","len"=>6,"dec"=>0,"offset"=>12),
  					 array ("name"=>"TITLE","abap"=>"C","len"=>15,"dec"=>0,"offset"=>18),
  					 array ("name"=>"NAME","abap"=>"C","len"=>35,"dec"=>0,"offset"=>33),
  					 array ("name"=>"NAME_2","abap"=>"C","len"=>35,"dec"=>0,"offset"=>68),
  					 array ("name"=>"NAME_3","abap"=>"C","len"=>35,"dec"=>0,"offset"=>103),
  					 array ("name"=>"NAME_4","abap"=>"C","len"=>35,"dec"=>0,"offset"=>138),
  					 array ("name"=>"STREET","abap"=>"C","len"=>35,"dec"=>0,"offset"=>173),
  					 array ("name"=>"COUNTRY","abap"=>"C","len"=>3,"dec"=>0,"offset"=>208),
  					 array ("name"=>"COUNTR_ISO","abap"=>"C","len"=>2,"dec"=>0,"offset"=>211),
  					 array ("name"=>"POSTL_CODE","abap"=>"C","len"=>10,"dec"=>0,"offset"=>213),
  					 array ("name"=>"POBX_PCD","abap"=>"C","len"=>10,"dec"=>0,"offset"=>223),
  					 array ("name"=>"POBX_CTY","abap"=>"C","len"=>35,"dec"=>0,"offset"=>233),
  					 array ("name"=>"CITY","abap"=>"C","len"=>35,"dec"=>0,"offset"=>268),
  					 array ("name"=>"DISTRICT","abap"=>"C","len"=>35,"dec"=>0,"offset"=>303),
  					 array ("name"=>"REGION","abap"=>"C","len"=>3,"dec"=>0,"offset"=>338),
  					 array ("name"=>"PO_BOX","abap"=>"C","len"=>10,"dec"=>0,"offset"=>341),
  					 array ("name"=>"TELEPHONE","abap"=>"C","len"=>16,"dec"=>0,"offset"=>351),
  					 array ("name"=>"TELEPHONE2","abap"=>"C","len"=>16,"dec"=>0,"offset"=>367),
  					 array ("name"=>"TELEBOX","abap"=>"C","len"=>15,"dec"=>0,"offset"=>383),
  					 array ("name"=>"FAX_NUMBER","abap"=>"C","len"=>31,"dec"=>0,"offset"=>398),
  					 array ("name"=>"TELETEX_NO","abap"=>"C","len"=>30,"dec"=>0,"offset"=>429),
  					 array ("name"=>"TELEX_NO","abap"=>"C","len"=>30,"dec"=>0,"offset"=>459),
  					 array ("name"=>"LANGU","abap"=>"C","len"=>1,"dec"=>0,"offset"=>489),
  					 array ("name"=>"LANGU_ISO","abap"=>"C","len"=>2,"dec"=>0,"offset"=>490),
  					 array ("name"=>"UNLOAD_PT","abap"=>"C","len"=>25,"dec"=>0,"offset"=>492),
  					 array ("name"=>"TRANSPZONE","abap"=>"C","len"=>10,"dec"=>0,"offset"=>517),
  					 array ("name"=>"TAXJURCODE","abap"=>"C","len"=>15,"dec"=>0,"offset"=>527),
  					 array ("name"=>"ADDRESS","abap"=>"C","len"=>10,"dec"=>0,"offset"=>542),
  					 array ("name"=>"PRIV_ADDR","abap"=>"C","len"=>10,"dec"=>0,"offset"=>552),
  					 array ("name"=>"ADDR_TYPE","abap"=>"C","len"=>1,"dec"=>0,"offset"=>562),
  					 array ("name"=>"ADDR_ORIG","abap"=>"C","len"=>1,"dec"=>0,"offset"=>563),
  					 array ("name"=>"ADDR_LINK","abap"=>"C","len"=>10,"dec"=>0,"offset"=>564),
  					 array ("name"=>"REFOBJTYPE","abap"=>"C","len"=>10,"dec"=>0,"offset"=>574),
  					 array ("name"=>"REFOBJKEY","abap"=>"C","len"=>70,"dec"=>0,"offset"=>584),
  					 array ("name"=>"REFLOGSYS","abap"=>"C","len"=>10,"dec"=>0,"offset"=>654)
  					)
  			),
  			 array (
  				 "name"=>"ORDER_SCHEDULES_IN",
  				 "type"=>"TABLE",
  				 "optional"=>"0",
  				 "def"=> array (
  					 array ("name"=>"ITM_NUMBER","abap"=>"N","len"=>6,"dec"=>0,"offset"=>0),
  					 array ("name"=>"SCHED_LINE","abap"=>"N","len"=>4,"dec"=>0,"offset"=>6),
  					 array ("name"=>"REQ_DATE","abap"=>"D","len"=>8,"dec"=>0,"offset"=>10),
  					 array ("name"=>"DATE_TYPE","abap"=>"C","len"=>1,"dec"=>0,"offset"=>18),
  					 array ("name"=>"REQ_TIME","abap"=>"T","len"=>6,"dec"=>0,"offset"=>19),
  					 array ("name"=>"REQ_QTY","abap"=>"P","len"=>7,"dec"=>3,"offset"=>25),
  					 array ("name"=>"REQ_DLV_BL","abap"=>"C","len"=>2,"dec"=>0,"offset"=>32),
  					 array ("name"=>"SCHED_TYPE","abap"=>"C","len"=>2,"dec"=>0,"offset"=>34),
  					 array ("name"=>"TP_DATE","abap"=>"D","len"=>8,"dec"=>0,"offset"=>36),
  					 array ("name"=>"MS_DATE","abap"=>"D","len"=>8,"dec"=>0,"offset"=>44),
  					 array ("name"=>"LOAD_DATE","abap"=>"D","len"=>8,"dec"=>0,"offset"=>52),
  					 array ("name"=>"GI_DATE","abap"=>"D","len"=>8,"dec"=>0,"offset"=>60),
  					 array ("name"=>"TP_TIME","abap"=>"T","len"=>6,"dec"=>0,"offset"=>68),
  					 array ("name"=>"MS_TIME","abap"=>"T","len"=>6,"dec"=>0,"offset"=>74),
  					 array ("name"=>"LOAD_TIME","abap"=>"T","len"=>6,"dec"=>0,"offset"=>80),
  					 array ("name"=>"GI_TIME","abap"=>"T","len"=>6,"dec"=>0,"offset"=>86),
  					 array ("name"=>"REFOBJTYPE","abap"=>"C","len"=>10,"dec"=>0,"offset"=>92),
  					 array ("name"=>"REFOBJKEY","abap"=>"C","len"=>70,"dec"=>0,"offset"=>102),
  					 array ("name"=>"REFLOGSYS","abap"=>"C","len"=>10,"dec"=>0,"offset"=>172),
  					 array ("name"=>"DLV_DATE","abap"=>"D","len"=>8,"dec"=>0,"offset"=>182),
  					 array ("name"=>"DLV_TIME","abap"=>"T","len"=>6,"dec"=>0,"offset"=>190),
  					 array ("name"=>"REL_TYPE","abap"=>"C","len"=>1,"dec"=>0,"offset"=>196),
  					 array ("name"=>"PLAN_SCHED_TYPE","abap"=>"C","len"=>1,"dec"=>0,"offset"=>197)
  					)
  			),
  			 array (
  				 "name"=>"ORDER_SCHEDULES_INX",
  				 "type"=>"TABLE",
  				 "optional"=>"0",
  				 "def"=> array (
  					 array ("name"=>"ITM_NUMBER","abap"=>"N","len"=>6,"dec"=>0,"offset"=>0),
  					 array ("name"=>"SCHED_LINE","abap"=>"N","len"=>4,"dec"=>0,"offset"=>6),
  					 array ("name"=>"UPDATEFLAG","abap"=>"C","len"=>1,"dec"=>0,"offset"=>10),
  					 array ("name"=>"REQ_DATE","abap"=>"C","len"=>1,"dec"=>0,"offset"=>11),
  					 array ("name"=>"DATE_TYPE","abap"=>"C","len"=>1,"dec"=>0,"offset"=>12),
  					 array ("name"=>"REQ_TIME","abap"=>"C","len"=>1,"dec"=>0,"offset"=>13),
  					 array ("name"=>"REQ_QTY","abap"=>"C","len"=>1,"dec"=>0,"offset"=>14),
  					 array ("name"=>"REQ_DLV_BL","abap"=>"C","len"=>1,"dec"=>0,"offset"=>15),
  					 array ("name"=>"SCHED_TYPE","abap"=>"C","len"=>1,"dec"=>0,"offset"=>16),
  					 array ("name"=>"TP_DATE","abap"=>"C","len"=>1,"dec"=>0,"offset"=>17),
  					 array ("name"=>"MS_DATE","abap"=>"C","len"=>1,"dec"=>0,"offset"=>18),
  					 array ("name"=>"LOAD_DATE","abap"=>"C","len"=>1,"dec"=>0,"offset"=>19),
  					 array ("name"=>"GI_DATE","abap"=>"C","len"=>1,"dec"=>0,"offset"=>20),
  					 array ("name"=>"TP_TIME","abap"=>"C","len"=>1,"dec"=>0,"offset"=>21),
  					 array ("name"=>"MS_TIME","abap"=>"C","len"=>1,"dec"=>0,"offset"=>22),
  					 array ("name"=>"LOAD_TIME","abap"=>"C","len"=>1,"dec"=>0,"offset"=>23),
  					 array ("name"=>"GI_TIME","abap"=>"C","len"=>1,"dec"=>0,"offset"=>24),
  					 array ("name"=>"REFOBJTYPE","abap"=>"C","len"=>10,"dec"=>0,"offset"=>25),
  					 array ("name"=>"REFOBJKEY","abap"=>"C","len"=>70,"dec"=>0,"offset"=>35),
  					 array ("name"=>"DLV_DATE","abap"=>"C","len"=>1,"dec"=>0,"offset"=>105),
  					 array ("name"=>"DLV_TIME","abap"=>"C","len"=>1,"dec"=>0,"offset"=>106),
  					 array ("name"=>"REL_TYPE","abap"=>"C","len"=>1,"dec"=>0,"offset"=>107),
  					 array ("name"=>"PLAN_SCHED_TYPE","abap"=>"C","len"=>1,"dec"=>0,"offset"=>108)
  					)
  			),
  			 array (
  				 "name"=>"ORDER_TEXT",
  				 "type"=>"TABLE",
  				 "optional"=>"0",
  				 "def"=> array (
  					 array ("name"=>"DOC_NUMBER","abap"=>"C","len"=>10,"dec"=>0,"offset"=>0),
  					 array ("name"=>"ITM_NUMBER","abap"=>"N","len"=>6,"dec"=>0,"offset"=>10),
  					 array ("name"=>"TEXT_ID","abap"=>"C","len"=>4,"dec"=>0,"offset"=>16),
  					 array ("name"=>"LANGU","abap"=>"C","len"=>1,"dec"=>0,"offset"=>20),
  					 array ("name"=>"LANGU_ISO","abap"=>"C","len"=>2,"dec"=>0,"offset"=>21),
  					 array ("name"=>"FORMAT_COL","abap"=>"C","len"=>2,"dec"=>0,"offset"=>23),
  					 array ("name"=>"TEXT_LINE","abap"=>"C","len"=>132,"dec"=>0,"offset"=>25),
  					 array ("name"=>"FUNCTION","abap"=>"C","len"=>3,"dec"=>0,"offset"=>157)
  					)
  			),
  			 array (
  				 "name"=>"PARTNERADDRESSES",
  				 "type"=>"TABLE",
  				 "optional"=>"0",
  				 "def"=> array (
  					 array ("name"=>"ADDR_NO","abap"=>"C","len"=>10,"dec"=>0,"offset"=>0),
  					 array ("name"=>"FORMOFADDR","abap"=>"C","len"=>20,"dec"=>0,"offset"=>10),
  					 array ("name"=>"NAME","abap"=>"C","len"=>40,"dec"=>0,"offset"=>30),
  					 array ("name"=>"NAME_2","abap"=>"C","len"=>40,"dec"=>0,"offset"=>70),
  					 array ("name"=>"NAME_3","abap"=>"C","len"=>40,"dec"=>0,"offset"=>110),
  					 array ("name"=>"NAME_4","abap"=>"C","len"=>40,"dec"=>0,"offset"=>150),
  					 array ("name"=>"C_O_NAME","abap"=>"C","len"=>40,"dec"=>0,"offset"=>190),
  					 array ("name"=>"CITY","abap"=>"C","len"=>40,"dec"=>0,"offset"=>230),
  					 array ("name"=>"DISTRICT","abap"=>"C","len"=>40,"dec"=>0,"offset"=>270),
  					 array ("name"=>"CITY_NO","abap"=>"C","len"=>12,"dec"=>0,"offset"=>310),
  					 array ("name"=>"POSTL_COD1","abap"=>"C","len"=>10,"dec"=>0,"offset"=>322),
  					 array ("name"=>"POSTL_COD2","abap"=>"C","len"=>10,"dec"=>0,"offset"=>332),
  					 array ("name"=>"POSTL_COD3","abap"=>"C","len"=>10,"dec"=>0,"offset"=>342),
  					 array ("name"=>"PO_BOX","abap"=>"C","len"=>10,"dec"=>0,"offset"=>352),
  					 array ("name"=>"PO_BOX_CIT","abap"=>"C","len"=>40,"dec"=>0,"offset"=>362),
  					 array ("name"=>"DELIV_DIS","abap"=>"C","len"=>15,"dec"=>0,"offset"=>402),
  					 array ("name"=>"STREET","abap"=>"C","len"=>40,"dec"=>0,"offset"=>417),
  					 array ("name"=>"STREET_NO","abap"=>"C","len"=>12,"dec"=>0,"offset"=>457),
  					 array ("name"=>"STR_ABBR","abap"=>"C","len"=>2,"dec"=>0,"offset"=>469),
  					 array ("name"=>"HOUSE_NO","abap"=>"C","len"=>10,"dec"=>0,"offset"=>471),
  					 array ("name"=>"STR_SUPPL1","abap"=>"C","len"=>40,"dec"=>0,"offset"=>481),
  					 array ("name"=>"STR_SUPPL2","abap"=>"C","len"=>40,"dec"=>0,"offset"=>521),
  					 array ("name"=>"LOCATION","abap"=>"C","len"=>40,"dec"=>0,"offset"=>561),
  					 array ("name"=>"BUILDING","abap"=>"C","len"=>10,"dec"=>0,"offset"=>601),
  					 array ("name"=>"FLOOR","abap"=>"C","len"=>10,"dec"=>0,"offset"=>611),
  					 array ("name"=>"ROOM_NO","abap"=>"C","len"=>10,"dec"=>0,"offset"=>621),
  					 array ("name"=>"COUNTRY","abap"=>"C","len"=>3,"dec"=>0,"offset"=>631),
  					 array ("name"=>"LANGU","abap"=>"C","len"=>1,"dec"=>0,"offset"=>634),
  					 array ("name"=>"REGION","abap"=>"C","len"=>3,"dec"=>0,"offset"=>635),
  					 array ("name"=>"SORT1","abap"=>"C","len"=>20,"dec"=>0,"offset"=>638),
  					 array ("name"=>"SORT2","abap"=>"C","len"=>20,"dec"=>0,"offset"=>658),
  					 array ("name"=>"TIME_ZONE","abap"=>"C","len"=>6,"dec"=>0,"offset"=>678),
  					 array ("name"=>"TAXJURCODE","abap"=>"C","len"=>15,"dec"=>0,"offset"=>684),
  					 array ("name"=>"ADR_NOTES","abap"=>"C","len"=>50,"dec"=>0,"offset"=>699),
  					 array ("name"=>"COMM_TYPE","abap"=>"C","len"=>3,"dec"=>0,"offset"=>749),
  					 array ("name"=>"TEL1_NUMBR","abap"=>"C","len"=>30,"dec"=>0,"offset"=>752),
  					 array ("name"=>"TEL1_EXT","abap"=>"C","len"=>10,"dec"=>0,"offset"=>782),
  					 array ("name"=>"FAX_NUMBER","abap"=>"C","len"=>30,"dec"=>0,"offset"=>792),
  					 array ("name"=>"FAX_EXTENS","abap"=>"C","len"=>10,"dec"=>0,"offset"=>822),
  					 array ("name"=>"STREET_LNG","abap"=>"C","len"=>60,"dec"=>0,"offset"=>832),
  					 array ("name"=>"DISTRCT_NO","abap"=>"C","len"=>8,"dec"=>0,"offset"=>892),
  					 array ("name"=>"CHCKSTATUS","abap"=>"C","len"=>1,"dec"=>0,"offset"=>900),
  					 array ("name"=>"PBOXCIT_NO","abap"=>"C","len"=>12,"dec"=>0,"offset"=>901),
  					 array ("name"=>"TRANSPZONE","abap"=>"C","len"=>10,"dec"=>0,"offset"=>913),
  					 array ("name"=>"HOUSE_NO2","abap"=>"C","len"=>10,"dec"=>0,"offset"=>923),
  					 array ("name"=>"E_MAIL","abap"=>"C","len"=>241,"dec"=>0,"offset"=>933),
  					 array ("name"=>"STR_SUPPL3","abap"=>"C","len"=>40,"dec"=>0,"offset"=>1174),
  					 array ("name"=>"TITLE","abap"=>"C","len"=>30,"dec"=>0,"offset"=>1214),
  					 array ("name"=>"COUNTRYISO","abap"=>"C","len"=>2,"dec"=>0,"offset"=>1244),
  					 array ("name"=>"LANGU_ISO","abap"=>"C","len"=>2,"dec"=>0,"offset"=>1246),
  					 array ("name"=>"BUILD_LONG","abap"=>"C","len"=>20,"dec"=>0,"offset"=>1248),
  					 array ("name"=>"REGIOGROUP","abap"=>"C","len"=>8,"dec"=>0,"offset"=>1268),
  					 array ("name"=>"HOME_CITY","abap"=>"C","len"=>40,"dec"=>0,"offset"=>1276),
  					 array ("name"=>"HOMECITYNO","abap"=>"C","len"=>12,"dec"=>0,"offset"=>1316),
  					 array ("name"=>"PCODE1_EXT","abap"=>"C","len"=>10,"dec"=>0,"offset"=>1328),
  					 array ("name"=>"PCODE2_EXT","abap"=>"C","len"=>10,"dec"=>0,"offset"=>1338),
  					 array ("name"=>"PCODE3_EXT","abap"=>"C","len"=>10,"dec"=>0,"offset"=>1348),
  					 array ("name"=>"PO_W_O_NO","abap"=>"C","len"=>1,"dec"=>0,"offset"=>1358),
  					 array ("name"=>"PO_BOX_REG","abap"=>"C","len"=>3,"dec"=>0,"offset"=>1359),
  					 array ("name"=>"POBOX_CTRY","abap"=>"C","len"=>3,"dec"=>0,"offset"=>1362),
  					 array ("name"=>"PO_CTRYISO","abap"=>"C","len"=>2,"dec"=>0,"offset"=>1365),
  					 array ("name"=>"HOMEPAGE","abap"=>"C","len"=>132,"dec"=>0,"offset"=>1367),
  					 array ("name"=>"DONT_USE_S","abap"=>"C","len"=>4,"dec"=>0,"offset"=>1499),
  					 array ("name"=>"DONT_USE_P","abap"=>"C","len"=>4,"dec"=>0,"offset"=>1503),
  					 array ("name"=>"HOUSE_NO3","abap"=>"C","len"=>10,"dec"=>0,"offset"=>1507),
  					 array ("name"=>"LANGU_CR","abap"=>"C","len"=>1,"dec"=>0,"offset"=>1517),
  					 array ("name"=>"LANGUCRISO","abap"=>"C","len"=>2,"dec"=>0,"offset"=>1518)
  					)
  			),
  			 array (
  				 "name"=>"RETURN",
  				 "type"=>"TABLE",
  				 "optional"=>"0",
  				 "def"=> array (
  					 array ("name"=>"TYPE","abap"=>"C","len"=>1,"dec"=>0,"offset"=>0),
  					 array ("name"=>"ID","abap"=>"C","len"=>20,"dec"=>0,"offset"=>1),
  					 array ("name"=>"NUMBER","abap"=>"N","len"=>3,"dec"=>0,"offset"=>21),
  					 array ("name"=>"MESSAGE","abap"=>"C","len"=>220,"dec"=>0,"offset"=>24),
  					 array ("name"=>"LOG_NO","abap"=>"C","len"=>20,"dec"=>0,"offset"=>244),
  					 array ("name"=>"LOG_MSG_NO","abap"=>"N","len"=>6,"dec"=>0,"offset"=>264),
  					 array ("name"=>"MESSAGE_V1","abap"=>"C","len"=>50,"dec"=>0,"offset"=>270),
  					 array ("name"=>"MESSAGE_V2","abap"=>"C","len"=>50,"dec"=>0,"offset"=>320),
  					 array ("name"=>"MESSAGE_V3","abap"=>"C","len"=>50,"dec"=>0,"offset"=>370),
  					 array ("name"=>"MESSAGE_V4","abap"=>"C","len"=>50,"dec"=>0,"offset"=>420),
  					 array ("name"=>"PARAMETER","abap"=>"C","len"=>32,"dec"=>0,"offset"=>470),
  					 array ("name"=>"ROW","abap"=>"I","len"=>4,"dec"=>0,"offset"=>504),
  					 array ("name"=>"FIELD","abap"=>"C","len"=>30,"dec"=>0,"offset"=>508),
  					 array ("name"=>"SYSTEM","abap"=>"C","len"=>10,"dec"=>0,"offset"=>538)
  					)
  			)
  		); 
  $fce = saprfc_function_define($rfc,"ZMCV_RFC_CREARPEDIDOS",$def);
*/